<!DOCTYPE html>
<html>

<head>
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <title>random</title>
</head>

<body onload="Core.Window.setTitle('random')">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>

<script>
    const action = function() {
        var content = document.getElementById('content');
        var charset = 'Il|'; // 'Il1|'
        var minsize = 50; // 10
        var maxsize = 100; // 20
        var size = Core.Math.randomInt(minsize, maxsize);
        var result = '';
        for (var i = 0; i < size; i++) {
            result += charset.charAt(Core.Math.randomInt(charset.length));
        }
        content.innerHTML = result;
    };
</script>

<div class="body">
  <div class="p-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="">Random</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p id="content">
            <script> action(); </script>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

</body>

</html>
