<!DOCTYPE html>
<html>

<head>
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <link rel="stylesheet" href="style.css">
  <title>Editor</title>
</head>

<body onload="Core.Window.setTitle('Editor')">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>

<div class="body">
  <div class="p-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="">Monospace Text Editor</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="pb-3">
    <div class="container">
      <div class="row">
        <textarea id="text" class="form-control text-editor" autocapitalize="none" autocomplete="off" spellcheck="false" placeholder=" !&quot;#$%&amp;'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~"></textarea>
      </div>
    </div>
  </div>
</div>

</body>

</html>
