<!DOCTYPE html>
<html>
<head>
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <link rel="stylesheet" href="style.css">
  <script src="script.js"></script>
  <title>랜타디 ReZero 미션 목록</title>
</head>
<body>
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>

<div class="body">
  <div class="py-4 px-1">
    <div class="container">
      <div class="row">
        <div class="col-md-12 py-2">
          <h1>랜타디 ReZero 미션 목록</h1>
        </div>
        <div class="col-md-12 py-2">
          <form id=0 data-mission="description" ><fieldset>
            <legend><strong>타워 설명</strong></legend>
            <strong>E</strong> : 에픽<br>
            <strong>U</strong> : 유니크<br>
            <strong>R</strong> : 레어<br>
            <strong>M</strong> : 매직<br>
            <strong>N</strong> : 노말<br>
          </fieldset></form>
        </div>
        <div class="col-md-12 py-2">
          <form id=1 data-mission="unluckseven"><fieldset>
            <legend><strong>1. 언럭키세븐 : 미네랄 300</strong></legend>
            (★ <strong>R</strong> 종류 상관없이 7기 ★)<br>
          </fieldset></form>
        </div>
        <div class="col-md-12 py-2">
          <form id=2 data-mission="unluckluck"><fieldset>
            <legend><strong>2. 악운도 운이다 : 미네랄 300</strong></legend>
            (★ <strong>U</strong> 종류 상관없이 6기 ★)<br>
          </fieldset></form>
        </div>
        <div class="col-md-12 py-2">
          <form id=3 data-mission="thousandyears"><fieldset>
            <legend><strong>3. 천년의 기다림 : 유니크 시민 1기</strong></legend>
            (★ 보스 시민 5기 보유 ★)<br>
          </fieldset></form>
        </div>
        <div class="col-md-12 py-2">
          <form class="mission" id=4 data-mission="nounbalance"><fieldset>
            <legend><input type="radio" disabled=true id="nounbalance" data-mission="nounbalance"/>
              <strong>4. 편식은 금물 : 미네랄 300</strong></legend>
            (★ <b>N</b> 종류별로 1기씩 ★)<br> 
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>N</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    드라군 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="nounbalance" data-tower="N_Dragoon" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/N_Dragoon.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="nounbalance" data-tower="N_Dragoon" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    레이스 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="nounbalance" data-tower="N_Wraith" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/N_Wraith.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="nounbalance" data-tower="N_Wraith" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    마린 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="nounbalance" data-tower="N_Marine" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/N_Marine.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="nounbalance" data-tower="N_Marine" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    뮤탈 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="nounbalance" data-tower="N_Mutalisk" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/N_Mutalisk.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="nounbalance" data-tower="N_Mutalisk" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    벌쳐 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="nounbalance" data-tower="N_Vulture" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/N_Vulture.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="nounbalance" data-tower="N_Vulture" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    스카웃 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="nounbalance" data-tower="N_Scout" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/N_Scout.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="nounbalance" data-tower="N_Scout" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    울트라 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="nounbalance" data-tower="N_Ultralisk" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/N_Ultralisk.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="nounbalance" data-tower="N_Ultralisk" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    히드라 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="nounbalance" data-tower="N_Hydralisk" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/N_Hydralisk.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="nounbalance" data-tower="N_Hydralisk" data-index=0 >
                  </div>
                </div>
              </div>
            </div>
          </fieldset></form>
        </div>
        <div class="col-md-12 py-2">
          <form class="mission" id=5 data-mission="weareone"><fieldset>
            <legend><input type="radio" disabled=true id="weareone" data-mission="weareone"/>
              <strong>5. 지긋지긋해 하늘이 Gray색이야 : 미네랄 300, 가스 100</strong></legend>
            (★ <b>M</b> 종류별로 1기씩 ★)<br> 
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>M</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    남자 고스트 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="weareone" data-tower="M_MGhost" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_MGhost.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="weareone" data-tower="M_MGhost" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    디파일러 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="weareone" data-tower="M_Defiler" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Defiler.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="weareone" data-tower="M_Defiler" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    다크 템플러 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="weareone" data-tower="M_Dark_Templar" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Dark_Templar.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="weareone" data-tower="M_Dark_Templar" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    스카웃 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="weareone" data-tower="M_Scout" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Scout.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="weareone" data-tower="M_Scout" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    아칸 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="weareone" data-tower="M_Archon" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Archon.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="weareone" data-tower="M_Archon" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    여자 고스트 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="weareone" data-tower="M_FGhost" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_FGhost.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="weareone" data-tower="M_FGhost" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    탱크 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="weareone" data-tower="M_Tank" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Tank.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="weareone" data-tower="M_Tank" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    파이어뱃 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="weareone" data-tower="M_Firebat" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Firebat.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="weareone" data-tower="M_Firebat" data-index=0 >
                  </div>
                </div>
              </div>
            </div>
          </fieldset></form>
        </div>
        <div class="col-md-12 py-2">
          <form class="mission" id=6 data-mission="strangehobby"><fieldset>
            <legend><input type="radio" disabled=true id="strangehobby" data-mission="strangehobby"/>
              <strong>6. 이상한 사람의 취미생활 : 보스 시민 3기</strong></legend>
            (★ 리버를 제외한 모든 <b>U</b> 유닛 1기씩 ★)<br> 
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>U</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    가디언 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="strangehobby" data-tower="U_Guardian" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Guardian.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="strangehobby" data-tower="U_Guardian" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    다크 아칸 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="strangehobby" data-tower="U_Dark_Archon" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Dark_Archon.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="strangehobby" data-tower="U_Dark_Archon" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    마린 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="strangehobby" data-tower="U_Marine" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Marine.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="strangehobby" data-tower="U_Marine" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    발키리 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="strangehobby" data-tower="U_Valkyrie" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Valkyrie.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="strangehobby" data-tower="U_Valkyrie" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    저글링 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="strangehobby" data-tower="U_Zergling" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Zergling.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="strangehobby" data-tower="U_Zergling" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    하이 템플러 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="strangehobby" data-tower="U_High_Templar" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_High_Templar.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="strangehobby" data-tower="U_High_Templar" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    히드라 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="strangehobby" data-tower="U_Hydralisk" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Hydralisk.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="strangehobby" data-tower="U_Hydralisk" data-index=0 >
                  </div>
                </div>
              </div>
            </div>
          </fieldset></form>
        </div>
        <div class="col-md-12 py-2">
          <form class="mission" id=7 data-mission="location"><fieldset>
            <legend><input type="radio" disabled=true id="location" data-mission="location"/>
              <strong>7. 자리 미션 : 유니크 시민 1기</strong></legend>
            <font color="blue">(★ 파랑은 타워 7, 게이트 1 생산으로 클리어 가능 ★)</font><br> 
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong><font color="red">빨강</font> M</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    디파일러 7 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Defiler" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Defiler.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Defiler" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Defiler" data-index=1 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Defiler.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Defiler" data-index=1 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Defiler" data-index=2 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Defiler.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Defiler" data-index=2 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Defiler" data-index=3 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Defiler.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Defiler" data-index=3 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Defiler" data-index=4 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Defiler.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Defiler" data-index=4 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Defiler" data-index=5 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Defiler.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Defiler" data-index=5 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Defiler" data-index=6 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Defiler.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Defiler" data-index=6 >
                  </div>
                </div>
              </div>
            </div>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong><font color="blue">파랑</font> M</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    다크 템플러 7+1 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Dark_Templar" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Dark_Templar.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Dark_Templar" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Dark_Templar" data-index=1 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Dark_Templar.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Dark_Templar" data-index=1 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Dark_Templar" data-index=2 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Dark_Templar.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Dark_Templar" data-index=2 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Dark_Templar" data-index=3 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Dark_Templar.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Dark_Templar" data-index=3 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Dark_Templar" data-index=4 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Dark_Templar.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Dark_Templar" data-index=4 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Dark_Templar" data-index=5 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Dark_Templar.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Dark_Templar" data-index=5 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Dark_Templar" data-index=6 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Dark_Templar.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Dark_Templar" data-index=6 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Dark_Templar" data-index=7 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Dark_Templar.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Dark_Templar" data-index=7 >
                  </div>
                </div>
              </div>
            </div>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong><font color="teal">연두</font> M</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    여자 고스트 7 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_FGhost" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_FGhost.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_FGhost" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_FGhost" data-index=1 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_FGhost.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_FGhost" data-index=1 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_FGhost" data-index=2 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_FGhost.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_FGhost" data-index=2 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_FGhost" data-index=3 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_FGhost.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_FGhost" data-index=3 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_FGhost" data-index=4 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_FGhost.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_FGhost" data-index=4 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_FGhost" data-index=5 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_FGhost.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_FGhost" data-index=5 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_FGhost" data-index=6 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_FGhost.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_FGhost" data-index=6 >
                  </div>
                </div>
              </div>
            </div>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong><font color="purple">보라</font> M</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    파이어뱃 7 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Firebat" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Firebat.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Firebat" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Firebat" data-index=1 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Firebat.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Firebat" data-index=1 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Firebat" data-index=2 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Firebat.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Firebat" data-index=2 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Firebat" data-index=3 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Firebat.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Firebat" data-index=3 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Firebat" data-index=4 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Firebat.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Firebat" data-index=4 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Firebat" data-index=5 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Firebat.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Firebat" data-index=5 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Firebat" data-index=6 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Firebat.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Firebat" data-index=6 >
                  </div>
                </div>
              </div>
            </div>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong><font color="orange">주황</font> M</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    탱크 7 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Tank" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Tank.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Tank" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Tank" data-index=1 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Tank.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Tank" data-index=1 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Tank" data-index=2 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Tank.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Tank" data-index=2 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Tank" data-index=3 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Tank.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Tank" data-index=3 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Tank" data-index=4 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Tank.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Tank" data-index=4 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Tank" data-index=5 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Tank.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Tank" data-index=5 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Tank" data-index=6 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Tank.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Tank" data-index=6 >
                  </div>
                </div>
              </div>
            </div>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong><font color="brown">갈색</font> M</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    아칸 7 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Archon" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Archon.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Archon" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Archon" data-index=1 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Archon.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Archon" data-index=1 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Archon" data-index=2 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Archon.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Archon" data-index=2 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Archon" data-index=3 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Archon.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Archon" data-index=3 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Archon" data-index=4 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Archon.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Archon" data-index=4 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Archon" data-index=5 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Archon.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Archon" data-index=5 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="location" data-tower="M_Archon" data-index=6 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Archon.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="location" data-tower="M_Archon" data-index=6 >
                  </div>
                </div>
              </div>
            </div>
          </fieldset></form>
        </div>
        <div class="col-md-12 py-2">
          <form class="mission" id=8 data-mission="themanthewoman"><fieldset>
            <legend><input type="radio" disabled=true id="themanthewoman" data-mission="themanthewoman"/>
              <strong>8. 그 남자 그리고 그 여자 : 미네랄 400</strong></legend>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>M</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    남자 고스트 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="themanthewoman" data-tower="M_MGhost" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_MGhost.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="themanthewoman" data-tower="M_MGhost" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    여자 고스트 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="themanthewoman" data-tower="M_FGhost" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_FGhost.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="themanthewoman" data-tower="M_FGhost" data-index=0 >
                  </div>
                </div>
              </div>
            </div>
          </fieldset></form>
        </div>
        <div class="col-md-12 py-2">
          <form class="mission" id=9 data-mission="starship"><fieldset>
            <legend><input type="radio" disabled=true id="starship" data-mission="starship"/>
              <strong>9. 스타쉽 : 유니크 시민 1기</strong></legend>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>U</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    발키리 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="starship" data-tower="U_Valkyrie" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Valkyrie.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="starship" data-tower="U_Valkyrie" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    가디언 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="starship" data-tower="U_Guardian" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Guardian.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="starship" data-tower="U_Guardian" data-index=0 >
                  </div>
                </div>
              </div>
            </div>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>R</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    파이어뱃 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="starship" data-tower="R_Firebat" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Firebat.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="starship" data-tower="R_Firebat" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    디바우러 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="starship" data-tower="R_Devourer" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Devourer.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="starship" data-tower="R_Devourer" data-index=0 >
                  </div>
                </div>
              </div>
            </div>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>M</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    탱크 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="starship" data-tower="M_Tank" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Tank.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="starship" data-tower="M_Tank" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    디파일러 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="starship" data-tower="M_Defiler" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Defiler.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="starship" data-tower="M_Defiler" data-index=0 >
                  </div>
                </div>
              </div>
            </div>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>N</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    벌쳐 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="starship" data-tower="N_Vulture" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/N_Vulture.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="starship" data-tower="N_Vulture" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    뮤탈 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="starship" data-tower="N_Mutalisk" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/N_Mutalisk.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="starship" data-tower="N_Mutalisk" data-index=0 >
                  </div>
                </div>
              </div>
            </div>
          </fieldset></form>
        </div>
        <div class="col-md-12 py-2">
          <form class="mission" id=10 data-mission="independence"><fieldset>
            <legend><input type="radio" disabled=true id="independence" data-mission="independence"/>
              <strong>10. 인디펜던스 : 유니크 시민 1기</strong></legend>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>U</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    발키리 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="independence" data-tower="U_Valkyrie" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Valkyrie.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="independence" data-tower="U_Valkyrie" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    리버 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="independence" data-tower="U_Reaver" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Reaver.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="independence" data-tower="U_Reaver" data-index=0 >
                  </div>
                </div>
              </div>
            </div>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>R</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    파이어뱃 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="independence" data-tower="R_Firebat" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Firebat.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="independence" data-tower="R_Firebat" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    드라군 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="independence" data-tower="R_Dragoon" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Dragoon.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="independence" data-tower="R_Dragoon" data-index=0 >
                  </div>
                </div>
              </div>
            </div>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>M</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    탱크 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="independence" data-tower="M_Tank" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Tank.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="independence" data-tower="M_Tank" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    아칸 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="independence" data-tower="M_Archon" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Archon.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="independence" data-tower="M_Archon" data-index=0 >
                  </div>
                </div>
              </div>
            </div>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>N</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    벌쳐 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="independence" data-tower="N_Vulture" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/N_Vulture.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="independence" data-tower="N_Vulture" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    드라군 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="independence" data-tower="N_Dragoon" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/N_Dragoon.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="independence" data-tower="N_Dragoon" data-index=0 >
                  </div>
                </div>
              </div>
            </div>
          </fieldset></form>
        </div>
        <div class="col-md-12 py-2">
          <form class="mission" id=11 data-mission="district9"><fieldset>
            <legend><input type="radio" disabled=true id="district9" data-mission="district9"/>
              <strong>11. 디스트릭트 9 (= 디나인) : 레어 시민 2기</strong></legend>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>R</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    촉수 3 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="district9" data-tower="R_Sunken" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Sunken.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="district9" data-tower="R_Sunken" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="district9" data-tower="R_Sunken" data-index=1 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Sunken.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="district9" data-tower="R_Sunken" data-index=1 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="district9" data-tower="R_Sunken" data-index=2 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Sunken.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="district9" data-tower="R_Sunken" data-index=2 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    아비터 3 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="district9" data-tower="R_Arbiter" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Arbiter.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="district9" data-tower="R_Arbiter" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="district9" data-tower="R_Arbiter" data-index=1 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Arbiter.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="district9" data-tower="R_Arbiter" data-index=1 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="district9" data-tower="R_Arbiter" data-index=2 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Arbiter.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="district9" data-tower="R_Arbiter" data-index=2 >
                  </div>
                </div>
              </div>
            </div>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>M</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    여자 고스트 3 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="district9" data-tower="M_FGhost" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_FGhost.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="district9" data-tower="M_FGhost" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="district9" data-tower="M_FGhost" data-index=1 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_FGhost.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="district9" data-tower="M_FGhost" data-index=1 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="district9" data-tower="M_FGhost" data-index=2 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_FGhost.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="district9" data-tower="M_FGhost" data-index=2 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    아칸 3 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="district9" data-tower="M_Archon" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Archon.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="district9" data-tower="M_Archon" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="district9" data-tower="M_Archon" data-index=1 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Archon.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="district9" data-tower="M_Archon" data-index=1 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="district9" data-tower="M_Archon" data-index=2 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Archon.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="district9" data-tower="M_Archon" data-index=2 >
                  </div>
                </div>
              </div>
            </div>
          </fieldset></form>
        </div>
        <div class="col-md-12 py-2">
          <form class="mission" id=12 data-mission="nadanada"><fieldset>
            <legend><input type="radio" disabled=true id="nadanada" data-mission="nadanada"/>
              <strong>12. 나빼고 다 깼네 나빼고 다 : 에픽 시민 1기</strong></legend>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>U</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    리버 3 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="nadanada" data-tower="U_Reaver" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Reaver.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="nadanada" data-tower="U_Reaver" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="nadanada" data-tower="U_Reaver" data-index=1 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Reaver.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="nadanada" data-tower="U_Reaver" data-index=1 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="nadanada" data-tower="U_Reaver" data-index=2 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Reaver.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="nadanada" data-tower="U_Reaver" data-index=2 >
                  </div>
                </div>
              </div>
            </div>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>R</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    레이스 3 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="nadanada" data-tower="R_Wraith" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Wraith.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="nadanada" data-tower="R_Wraith" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="nadanada" data-tower="R_Wraith" data-index=1 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Wraith.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="nadanada" data-tower="R_Wraith" data-index=1 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="nadanada" data-tower="R_Wraith" data-index=2 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Wraith.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="nadanada" data-tower="R_Wraith" data-index=2 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    촉수 3 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="nadanada" data-tower="R_Sunken" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Sunken.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="nadanada" data-tower="R_Sunken" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="nadanada" data-tower="R_Sunken" data-index=1 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Sunken.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="nadanada" data-tower="R_Sunken" data-index=1 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="nadanada" data-tower="R_Sunken" data-index=2 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Sunken.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="nadanada" data-tower="R_Sunken" data-index=2 >
                  </div>
                </div>
              </div>
            </div>
          </fieldset></form>
        </div>
        <div class="col-md-12 py-2">
          <form class="mission" id=13 data-mission="angelgame"><fieldset>
            <legend><input type="radio" disabled=true id="angelgame" data-mission="angelgame"/>
              <strong>13. 천사의 게임들 : 에픽 시민 1기, 미네랄 1000, 가스 4</strong></legend>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>E</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    거인 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="angelgame" data-tower="E_Giant" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/E_Giant.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="angelgame" data-tower="E_Giant" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    핵 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="angelgame" data-tower="E_Nuclear" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/E_Nuclear.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="angelgame" data-tower="E_Nuclear" data-index=0 >
                  </div>
                </div>
              </div>
            </div>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>U</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    리버 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="angelgame" data-tower="U_Reaver" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Reaver.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="angelgame" data-tower="U_Reaver" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    하이 템플러 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="angelgame" data-tower="U_High_Templar" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_High_Templar.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="angelgame" data-tower="U_High_Templar" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    다크 아칸 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="angelgame" data-tower="U_Dark_Archon" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Dark_Archon.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="angelgame" data-tower="U_Dark_Archon" data-index=0 >
                  </div>
                </div>
              </div>
            </div>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>R</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    드라군 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="angelgame" data-tower="R_Dragoon" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Dragoon.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="angelgame" data-tower="R_Dragoon" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    촉수 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="angelgame" data-tower="R_Sunken" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Sunken.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="angelgame" data-tower="R_Sunken" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    디바우러 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="angelgame" data-tower="R_Devourer" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Devourer.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="angelgame" data-tower="R_Devourer" data-index=0 >
                  </div>
                </div>
              </div>
            </div>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>M</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    아칸 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="angelgame" data-tower="M_Archon" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Archon.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="angelgame" data-tower="M_Archon" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    스카웃 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="angelgame" data-tower="M_Scout" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Scout.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="angelgame" data-tower="M_Scout" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    탱크 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="angelgame" data-tower="M_Tank" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Tank.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="angelgame" data-tower="M_Tank" data-index=0 >
                  </div>
                </div>
              </div>
            </div>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>N</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    드라군 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="angelgame" data-tower="N_Dragoon" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/N_Dragoon.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="angelgame" data-tower="N_Dragoon" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    스카웃 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="angelgame" data-tower="N_Scout" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/N_Scout.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="angelgame" data-tower="N_Scout" data-index=0 >
                  </div>
                </div>
              </div>
            </div>
          </fieldset></form>
        </div>
        <div class="col-md-12 py-2">
          <form class="mission" id=14 data-mission="heart"><fieldset>
            <legend><input type="radio" disabled=true id="heart" data-mission="heart"/>
              <strong>14. 버림받은 자들의 심장 : 라이프 6</strong></legend>
            <font color="red">(★ 빨강은 <b>N</b> 2마리씩 보유하면 클리어 ★)</font><br> 
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>R</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    골리앗 3 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="heart" data-tower="R_Goliath" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Goliath.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="heart" data-tower="R_Goliath" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="heart" data-tower="R_Goliath" data-index=1 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Goliath.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="heart" data-tower="R_Goliath" data-index=1 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="heart" data-tower="R_Goliath" data-index=2 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Goliath.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="heart" data-tower="R_Goliath" data-index=2 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    디파일러 3 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="heart" data-tower="R_Defiler" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Defiler.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="heart" data-tower="R_Defiler" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="heart" data-tower="R_Defiler" data-index=1 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Defiler.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="heart" data-tower="R_Defiler" data-index=1 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="heart" data-tower="R_Defiler" data-index=2 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Defiler.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="heart" data-tower="R_Defiler" data-index=2 >
                  </div>
                </div>
              </div>
            </div>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>N</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    울트라 3 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="heart" data-tower="N_Ultralisk" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/N_Ultralisk.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="heart" data-tower="N_Ultralisk" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="heart" data-tower="N_Ultralisk" data-index=1 />
                    <br>
                    <img class="img-custom-tower" src="./image/N_Ultralisk.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="heart" data-tower="N_Ultralisk" data-index=1 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="heart" data-tower="N_Ultralisk" data-index=2 />
                    <br>
                    <img class="img-custom-tower" src="./image/N_Ultralisk.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="heart" data-tower="N_Ultralisk" data-index=2 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    뮤탈 3 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="heart" data-tower="N_Mutalisk" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/N_Mutalisk.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="heart" data-tower="N_Mutalisk" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="heart" data-tower="N_Mutalisk" data-index=1 />
                    <br>
                    <img class="img-custom-tower" src="./image/N_Mutalisk.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="heart" data-tower="N_Mutalisk" data-index=1 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="heart" data-tower="N_Mutalisk" data-index=2 />
                    <br>
                    <img class="img-custom-tower" src="./image/N_Mutalisk.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="heart" data-tower="N_Mutalisk" data-index=2 >
                  </div>
                </div>
              </div>
            </div>
          </fieldset></form>
        </div>
        <div class="col-md-12 py-2">
          <form class="mission" id=15 data-mission="flying"><fieldset>
            <legend><input type="radio" disabled=true id="flying" data-mission="flying"/>
              <strong>15. 날아올라라 주작이여 : 보스 시민 2기</strong></legend>
            (★ 에픽 제외 모든 공중유닛 1기씩 ★)<br> 
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>U</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    발키리 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="flying" data-tower="U_Valkyrie" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Valkyrie.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="flying" data-tower="U_Valkyrie" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    가디언 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="flying" data-tower="U_Guardian" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Guardian.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="flying" data-tower="U_Guardian" data-index=0 >
                  </div>
                </div>
              </div>
            </div>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>R</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    디바우러 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="flying" data-tower="R_Devourer" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Devourer.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="flying" data-tower="R_Devourer" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    아비터 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="flying" data-tower="R_Arbiter" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Arbiter.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="flying" data-tower="R_Arbiter" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    레이스 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="flying" data-tower="R_Wraith" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Wraith.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="flying" data-tower="R_Wraith" data-index=0 >
                  </div>
                </div>
              </div>
            </div>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>M</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    스카웃 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="flying" data-tower="M_Scout" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Scout.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="flying" data-tower="M_Scout" data-index=0 >
                  </div>
                </div>
              </div>
            </div>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>N</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    뮤탈 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="flying" data-tower="N_Mutalisk" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/N_Mutalisk.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="flying" data-tower="N_Mutalisk" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    스카웃 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="flying" data-tower="N_Scout" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/N_Scout.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="flying" data-tower="N_Scout" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    레이스 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="flying" data-tower="N_Wraith" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/N_Wraith.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="flying" data-tower="N_Wraith" data-index=0 >
                  </div>
                </div>
              </div>
            </div>
          </fieldset></form>
        </div>
        <div class="col-md-12 py-2">
          <form class="mission" id=16 data-mission="bsss"><fieldset>
            <legend><input type="radio" disabled=true id="bsss" data-mission="bsss"/>
              <strong>16. 비선실세 : 가스 503</strong></legend>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>U</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    가디언 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="bsss" data-tower="U_Guardian" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Guardian.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="bsss" data-tower="U_Guardian" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    다크 아칸 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="bsss" data-tower="U_Dark_Archon" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Dark_Archon.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="bsss" data-tower="U_Dark_Archon" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    하이 템플러 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="bsss" data-tower="U_High_Templar" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_High_Templar.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="bsss" data-tower="U_High_Templar" data-index=0 >
                  </div>
                </div>
              </div>
            </div>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>R</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    디바우러 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="bsss" data-tower="R_Devourer" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Devourer.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="bsss" data-tower="R_Devourer" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    촉수 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="bsss" data-tower="R_Sunken" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/R_Sunken.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="bsss" data-tower="R_Sunken" data-index=0 >
                  </div>
                </div>
              </div>
            </div>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>M</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    디파일러 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="bsss" data-tower="M_Defiler" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Defiler.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="bsss" data-tower="M_Defiler" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    다크 템플러 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="bsss" data-tower="M_Dark_Templar" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Dark_Templar.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="bsss" data-tower="M_Dark_Templar" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    스카웃 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="bsss" data-tower="M_Scout" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_Scout.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="bsss" data-tower="M_Scout" data-index=0 >
                  </div>
                </div>
              </div>
            </div>
          </fieldset></form>
        </div>
        <div class="col-md-12 py-2">
          <form class="mission" id=17 data-mission="hidra"><fieldset>
            <legend><input type="radio" disabled=true id="hidra" data-mission="hidra"/>
              <strong>17. 하이드라의 저주 : 미네랄 400, 가스 400</strong></legend>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>U</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    히드라 3 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="hidra" data-tower="U_Hydralisk" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Hydralisk.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="hidra" data-tower="U_Hydralisk" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="hidra" data-tower="U_Hydralisk" data-index=1 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Hydralisk.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="hidra" data-tower="U_Hydralisk" data-index=1 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="hidra" data-tower="U_Hydralisk" data-index=2 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Hydralisk.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="hidra" data-tower="U_Hydralisk" data-index=2 >
                  </div>
                </div>
              </div>
            </div>
          </fieldset></form>
        </div>
        <div class="col-md-12 py-2">
          <form class="mission" id=18 data-mission="crazy"><fieldset>
            <legend><input type="radio" disabled=true id="crazy" data-mission="crazy"/>
              <strong>18. 어느 미치광이의 폭주 : 미네랄 100, 가스 525</strong></legend>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>E</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    핵 2 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="crazy" data-tower="E_Nuclear" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/E_Nuclear.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="crazy" data-tower="E_Nuclear" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="crazy" data-tower="E_Nuclear" data-index=1 />
                    <br>
                    <img class="img-custom-tower" src="./image/E_Nuclear.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="crazy" data-tower="E_Nuclear" data-index=1 >
                  </div>
                </div>
              </div>
            </div>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>M</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    남자 고스트 2 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="crazy" data-tower="M_MGhost" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_MGhost.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="crazy" data-tower="M_MGhost" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="crazy" data-tower="M_MGhost" data-index=1 />
                    <br>
                    <img class="img-custom-tower" src="./image/M_MGhost.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="crazy" data-tower="M_MGhost" data-index=1 >
                  </div>
                </div>
              </div>
            </div>
          </fieldset></form>
        </div>
        <div class="col-md-12 py-2">
          <form class="mission" id=19 data-mission="hellgate"><fieldset>
            <legend><input type="radio" disabled=true id="hellgate" data-mission="hellgate"/>
              <strong>19. 더 키스 오브 헬 게이트 : 유니크 시민 2기</strong></legend>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>E</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    지옥불 3 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="hellgate" data-tower="E_Hell_Fire" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/E_Hell_Fire.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="hellgate" data-tower="E_Hell_Fire" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="hellgate" data-tower="E_Hell_Fire" data-index=1 />
                    <br>
                    <img class="img-custom-tower" src="./image/E_Hell_Fire.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="hellgate" data-tower="E_Hell_Fire" data-index=1 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="hellgate" data-tower="E_Hell_Fire" data-index=2 />
                    <br>
                    <img class="img-custom-tower" src="./image/E_Hell_Fire.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="hellgate" data-tower="E_Hell_Fire" data-index=2 >
                  </div>
                </div>
              </div>
            </div>
          </fieldset></form>
        </div>
        <div class="col-md-12 py-2">
          <form class="mission" id=20 data-mission="orangeannoying"><fieldset>
            <legend><input type="radio" disabled=true id="orangeannoying" data-mission="orangeannoying"/>
              <strong>20. 귤먹다가 짜증이 : 미네랄 300</strong></legend>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>U</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    리버 3 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="orangeannoying" data-tower="U_Reaver" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Reaver.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="orangeannoying" data-tower="U_Reaver" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="orangeannoying" data-tower="U_Reaver" data-index=1 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Reaver.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="orangeannoying" data-tower="U_Reaver" data-index=1 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="orangeannoying" data-tower="U_Reaver" data-index=2 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Reaver.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="orangeannoying" data-tower="U_Reaver" data-index=2 >
                  </div>
                </div>
              </div>
            </div>
          </fieldset></form>
        </div>
        <div class="col-md-12 py-2">
          <form class="mission" id=21 data-mission="bigbigreaver"><fieldset>
            <legend><input type="radio" disabled=true id="bigbigreaver" data-mission="bigbigreaver"/>
              <strong>21. 카리스마 대빵 큰 리버 : 미네랄 800, 가스 800</strong></legend>
            <div class="row py-1">
              <div class="col col-custom-class p-1">
                <strong>U</strong>
              </div>
              <div class="col px-1">
                <div class="row">
                  <div class="col-md col-custom-tower p-1">
                    리버 5 
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="bigbigreaver" data-tower="U_Reaver" data-index=0 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Reaver.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="bigbigreaver" data-tower="U_Reaver" data-index=0 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="bigbigreaver" data-tower="U_Reaver" data-index=1 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Reaver.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="bigbigreaver" data-tower="U_Reaver" data-index=1 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="bigbigreaver" data-tower="U_Reaver" data-index=2 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Reaver.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="bigbigreaver" data-tower="U_Reaver" data-index=2 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="bigbigreaver" data-tower="U_Reaver" data-index=3 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Reaver.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="bigbigreaver" data-tower="U_Reaver" data-index=3 >
                  </div>
                  <div class="col-md col-custom-tower p-1">
                    <br>
                    <input type="checkbox" onclick="Script.toggleClicked(this)"
                        data-mission="bigbigreaver" data-tower="U_Reaver" data-index=4 />
                    <br>
                    <img class="img-custom-tower" src="./image/U_Reaver.php" draggable="false" onclick="Script.toggleClicked(this)" 
                        data-mission="bigbigreaver" data-tower="U_Reaver" data-index=4 >
                  </div>
                </div>
              </div>
            </div>
          </fieldset></form>
        </div>
        <div class="col-md-12 py-2">
          <form id=22 data-mission="changelog"><fieldset>
            <legend><strong>변경사항</strong></legend>
            <strong>2018.02.03</strong> : 오탈자, 보상 잘못 기록되어 있던 것 수정<br>
            <strong>2018.02.03</strong> : 미치광이 미션 조건 수정, 쩜드라의 저주 -> 하이드라의 저주 수정<br>
            <strong>2018.02.04</strong> : 귤짜증, 카리스마 미션 추가 / 자리미션 보상 기재<br>
            <strong>2018.08.24</strong> : 체크 박스 스크립트 추가<br>
            <strong>2018.08.25</strong> : 타워 스크린샷 추가<br>
            <strong>2018.08.26</strong> : 체크 박스 개수 추가<br>
            <strong>2018.08.28</strong> : 미션 정리<br>
            <strong>2019.09.29</strong> : Bootstrap 정리<br>
          </fieldset></form>
        </div>
        <div class="col-md-12 py-2">
          <font color="blue"><strong>Made by aMythos (Mythical#31274)</strong></font>
          <br>
          <strong>Edit & Host by him.nyit@gmail.com</strong>
        </div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
