<!DOCTYPE html>
<html>

<head>
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <title>Time - help topic</title>
</head>

<body onload="Core.Window.setTitle('Time - help topic')">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>
  <div class="p-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="">Help topic for Time application</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h3 class="">
            <a href="./">Go to Time Application</a>
          </h3>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">Explaination of parameters</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <table class="table">
            <thead class="thead-light">
              <tr>
                <th scope="col">Parameter</th>
                <th scope="col">Explaination</th>
                <th scope="col">Values</th>
                <th scope="col">Allowed modes</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">mode</th>
                <td>Sets display mode.</td>
                <td>
                  <ul>
                    <li><b>unix</b></li>
                    Unix timestamp in seconds.
                    <li><b>single</b></li>
                    Display last significant nonzero value of Unix timestamp.
                    <li><b>countdown</b></li>
                    Count to referenced time.
                    <li><b>countup</b></li>
                    Count from referenced time.
                    <li><b>simple</b></li>
                    Date and time in number.
                    <li><b>plain</b></li>
                    Date and time in full text.
                    <li><b>custom</b></li>
                    Customized time format specified by <b>format</b> parameter.
                    <li><b>him</b> (default)</li>
                    HIM timestamp.
                  </ul>
                </td>
                <td></td>
              </tr>
              <tr>
                <th scope="row">time</th>
                <td>Sets referenced time.</td>
                <td>
                  <ul>
                    <li>Single integer representing Unix timestamp.</li>
                    <li>String formatted using RFC 2822 or ISO 8601 standard.</li>
                  </ul>
                </td>
                <td>countdown<br>countup</td>
              </tr>
              <tr>
                <th scope="row">unit</th>
                <td>Sets display unit.</td>
                <td>
                  <ul>
                    <li>Single positive integer representing milliseconds.</li>
                    <li><b>second</b>, <b>sec</b></li>
                    <li><b>minute</b>, <b>min</b></li>
                    <li><b>hour</b>, <b>hr</b> (default)</li>
                    <li><b>day</b></li>
                    <li><b>week</b>, <b>wk</b></li>
                    <li><b>month</b>, <b>mo</b></li>
                    1/12th of Gregorian calendar year. (30.436 days)
                    <li><b>year</b>, <b>yr</b></li>
                    Average Gregorian calendar year. (365.24 days)
                  </ul>
                </td>
                <td>countdown<br>countup</td>
              </tr>
              <tr>
                <th scope="row">span</th>
                <td>Sets duration.</td>
                <td>
                  <ul>
                    <li>Single integer representing Unix timestamp.</li>
                    <li>String formatted using RFC 2822 or ISO 8601 standard.</li>
                    <li>Any number followed by space and units from above.</li>
                    e.g. <b>100 year</b>
                    <li><b>shorter</b></li>
                    654,321 hours.
                    <li><b>short</b></li>
                    765,432.1 hours.
                    <li><b>long</b> (default)</li>
                    876,543.21 hours.
                    <li><b>longer</b></li>
                    987,654.321 hours.
                  </ul>
                </td>
                <td>countdown</td>
              </tr>
              <tr>
                <th scope="row">base</th>
                <td>Sets base of number.</td>
                <td>
                  <ul>
                    <li>Any integer from 2 to 36.</li>
                    <li><b>binary</b>, <b>bin</b></li>
                    base 2.
                    <li><b>octal</b>, <b>oct</b></li>
                    base 8.
                    <li><b>decimal</b>, <b>dec</b> (default)</li>
                    base 10.
                    <li><b>hexadecimal</b>, <b>hex</b></li>
                    base 16.
                  </ul>
                </td>
                <td>unix<br>single</td>
              </tr>
              <tr>
                <th scope="row">digit</th>
                <td>Sets decimal digit.</td>
                <td>
                  <ul>
                    <li>Any positive integer.</li>
                    <li>Default value is 0 for <b>unix</b></li>
                    <li>Default value depends on unit, between 3 and 6.</li>
                  </ul>
                </td>
                <td>unix<br>countup<br>countdown</td>
              </tr>
              <tr>
                <th scope="row">space</th>
                <td>Sets space character.</td>
                <td>
                  <ul>
                    <li>Any string.</li>
                    <li><b>\n (%0A)</b></li>
                    new line (&lt;br&rt;).
                    <li><b>\t (%09)</b></li>
                    em space (&amp;emsp;).
                    <li>Default value is empty string.</li>
                  </ul>
                </td>
                <td>him</td>
              </tr>
              <tr>
                <th scope="row">line</th>
                <td>Sets line character.</td>
                <td>
                  <ul>
                    <li>Any string.</li>
                    <li><b>\n (%0A)</b> (default)</li>
                    new line.
                    <li><b>\t (%09)</b></li>
                    em space (&amp;emsp;).
                  </ul>
                </td>
                <td>simple<br>plain</td>
              </tr>
              <tr>
                <th scope="row">format</th>
                <td>Specifies custom time format.</td>
                <td>
                  <ul>
                    <li>PHP style date format. See table below.</li>
                    <li><b>YMdDHiTs</b> (default)</li>
                    Same output as HIM timestamp.
                  </ul>
                </td>
                <td>custom</td>
              </tr>
              <tr>
                <th scope="row">style</th>
                <td></td>
                <td>
                  <ul>
                    <li>Space(%20)-separated list of any of following.</li>
                    <li><b>default</b> (default)</li>
                    <li><b>light</b></li>
                    <li><b>dark</b></li>
                    <li><b>font-normal</b></li>
                    <li><b>font-bold</b></li>
                    <li><b>font-bolder</b></li>
                    <li><b>font-lighter</b></li>
                    <li><b>font-italic</b></li>
                    <li><b>font-oblique</b></li>
                    <li><b>monospace</b></li>
                    <li><b>serif</b></li>
                    <li><b>orbitron</b></li>
                  </ul>
                </td>
                <td></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">PHP style date format <a href="https://www.php.net/manual/en/function.date.php#refsect1-function.date-parameters">(link)</a></h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <table class="table">
            <thead class="thead-light">
              <tr>
                <th scope="col">Format character</th>
                <th scope="col">Description</th>
                <th scope="col">Example returned values</th>
              </tr>
            </thead>
            <tbody>
              <tr>
               <td style="text-align: center;"><em class="emphasis">Day</em></td>
               <td>---</td>
               <td>---</td>
              </tr>
              <tr>
               <td><em>d</em></td>
               <td>Day of the month, 2 digits with leading zeros</td>
               <td><em>01</em> to <em>31</em></td>
              </tr>
              <tr>
               <td><em>D</em></td>
               <td>A textual representation of a day, three letters</td>
               <td><em>Mon</em> through <em>Sun</em></td>
              </tr>
              <tr>
               <td><em>j</em></td>
               <td>Day of the month without leading zeros</td>
               <td><em>1</em> to <em>31</em></td>
              </tr>
              <tr>
               <td><em>l</em> (lowercase &#039;L&#039;)</td>
               <td>A full textual representation of the day of the week</td>
               <td><em>Sunday</em> through <em>Saturday</em></td>
              </tr>
              <tr>
               <td><em>N</em></td>
               <td>ISO-8601 numeric representation of the day of the week (added in
               PHP 5.1.0)</td>
               <td><em>1</em> (for Monday) through <em>7</em> (for Sunday)</td>
              </tr>
              <tr>
               <td><em>S</em></td>
               <td>English ordinal suffix for the day of the month, 2 characters</td>
               <td>
                <em>st</em>, <em>nd</em>, <em>rd</em> or
                <em>th</em>.  Works well with <em>j</em>
               </td>
              </tr>
              <tr>
               <td><em>w</em></td>
               <td>Numeric representation of the day of the week</td>
               <td><em>0</em> (for Sunday) through <em>6</em> (for Saturday)</td>
              </tr>
              <tr>
               <td><em>z</em></td>
               <td>The day of the year (starting from 0)</td>
               <td><em>0</em> through <em>365</em></td>
              </tr>
              <tr>
               <td style="text-align: center;"><em class="emphasis">Week</em></td>
               <td>---</td>
               <td>---</td>
              </tr>
              <tr>
               <td><s><em>W</em></s></td>
               <td><s>ISO-8601 week number of year, weeks starting on Monday</s></td>
               <td><s>Example: <em>42</em> (the 42nd week in the year)</s></td>
              </tr>
              <tr>
               <td style="text-align: center;"><em class="emphasis">Month</em></td>
               <td>---</td>
               <td>---</td>
              </tr>
              <tr>
               <td><em>F</em></td>
               <td>A full textual representation of a month, such as January or March</td>
               <td><em>January</em> through <em>December</em></td>
              </tr>
              <tr>
               <td><em>m</em></td>
               <td>Numeric representation of a month, with leading zeros</td>
               <td><em>01</em> through <em>12</em></td>
              </tr>
              <tr>
               <td><em>M</em></td>
               <td>A short textual representation of a month, three letters</td>
               <td><em>Jan</em> through <em>Dec</em></td>
              </tr>
              <tr>
               <td><em>n</em></td>
               <td>Numeric representation of a month, without leading zeros</td>
               <td><em>1</em> through <em>12</em></td>
              </tr>
              <tr>
               <td><em>t</em></td>
               <td>Number of days in the given month</td>
               <td><em>28</em> through <em>31</em></td>
              </tr>
              <tr>
               <td style="text-align: center;"><em class="emphasis">Year</em></td>
               <td>---</td>
               <td>---</td>
              </tr>
              <tr>
               <td><em>L</em></td>
               <td>Whether it&#039;s a leap year</td>
               <td><em>1</em> if it is a leap year, <em>0</em> otherwise.</td>
              </tr>
              <tr>
               <td><s><em>o</em></s></td>
               <td><s>ISO-8601 week-numbering year. This has the same value as
                <em>Y</em>, except that if the ISO week number
                (<em>W</em>) belongs to the previous or next year, that year
                is used instead. (added in PHP 5.1.0)</s></td>
               <td><s>Examples: <em>1999</em> or <em>2003</em></s></td>
              </tr>
              <tr>
               <td><em>Y</em></td>
               <td>A full numeric representation of a year, 4 digits</td>
               <td>Examples: <em>1999</em> or <em>2003</em></td>
              </tr>
              <tr>
               <td><em>y</em></td>
               <td>A two digit representation of a year</td>
               <td>Examples: <em>99</em> or <em>03</em></td>
              </tr>
              <tr>
               <td style="text-align: center;"><em class="emphasis">Time</em></td>
               <td>---</td>
               <td>---</td>
              </tr>
              <tr>
               <td><em>a</em></td>
               <td>Lowercase Ante meridiem and Post meridiem</td>
               <td><em>am</em> or <em>pm</em></td>
              </tr>
              <tr>
               <td><em>A</em></td>
               <td>Uppercase Ante meridiem and Post meridiem</td>
               <td><em>AM</em> or <em>PM</em></td>
              </tr>
              <tr>
               <td><em>B</em></td>
               <td>Swatch Internet time</td>
               <td><em>000</em> through <em>999</em></td>
              </tr>
              <tr>
               <td><em>g</em></td>
               <td>12-hour format of an hour without leading zeros</td>
               <td><em>1</em> through <em>12</em></td>
              </tr>
              <tr>
               <td><em>G</em></td>
               <td>24-hour format of an hour without leading zeros</td>
               <td><em>0</em> through <em>23</em></td>
              </tr>
              <tr>
               <td><em>h</em></td>
               <td>12-hour format of an hour with leading zeros</td>
               <td><em>01</em> through <em>12</em></td>
              </tr>
              <tr>
               <td><em>H</em></td>
               <td>24-hour format of an hour with leading zeros</td>
               <td><em>00</em> through <em>23</em></td>
              </tr>
              <tr>
               <td><em>i</em></td>
               <td>Minutes with leading zeros</td>
               <td><em>00</em> to <em>59</em></td>
              </tr>
              <tr>
               <td><em>s</em></td>
               <td>Seconds with leading zeros</td>
               <td><em>00</em> through <em>59</em></td>
              </tr>
              <tr>
               <td><s><em>u</em></s></td>
               <td><s>
                Microseconds (added in PHP 5.2.2). Note that
                <span class="function"><strong>date()</strong></span> will always generate
                <em>000000</em> since it takes an <span class="type"><a href="https://www.php.net/manual/en/language.types.integer.php" class="type integer">integer</a></span>
                parameter, whereas <span class="methodname"><a href="https://www.php.net/manual/en/datetime.format.php" class="methodname">DateTime::format()</a></span> does
                support microseconds if <a href="https://www.php.net/manual/en/class.datetime.php" class="classname">DateTime</a> was
                created with microseconds.
               </s></td>
               <td><s>Example: <em>654321</em></s></td>
              </tr>
              <tr>
               <td><em>v</em></td>
               <td>
                Milliseconds (added in PHP 7.0.0). Same note applies as for
                <em>u</em>.
               </td>
               <td>Example: <em>654</em></td>
              </tr>
              <tr>
               <td style="text-align: center;"><em class="emphasis">Timezone</em></td>
               <td>---</td>
               <td>---</td>
              </tr>
              <tr>
               <td><em>e</em></td>
               <td>Timezone identifier (added in PHP 5.1.0)</td>
               <td>Examples: <em>UTC</em>, <em>GMT</em>, <em>Atlantic/Azores</em></td>
              </tr>
              <tr>
               <td><em>I</em> (capital i)</td>
               <td>Whether or not the date is in daylight saving time</td>
               <td><em>1</em> if Daylight Saving Time, <em>0</em> otherwise.</td>
              </tr>
              <tr>
               <td><em>O</em></td>
               <td>Difference to Greenwich time (GMT) in hours</td>
               <td>Example: <em>+0200</em></td>
              </tr>
              <tr>
               <td><em>P</em></td>
               <td>Difference to Greenwich time (GMT) with colon between hours and minutes (added in PHP 5.1.3)</td>
               <td>Example: <em>+02:00</em></td>
              </tr>
              <tr>
               <td><em>T</em></td>
               <td>Timezone abbreviation</td>
               <td>Examples: <em>EST</em>, <em>MDT</em> ...</td>
              </tr>
              <tr>
               <td><em>Z</em></td>
               <td>Timezone offset in seconds. The offset for timezones west of UTC is always
               negative, and for those east of UTC is always positive.</td>
               <td><em>-43200</em> through <em>50400</em></td>
              </tr>
              <tr>
               <td style="text-align: center;"><em class="emphasis">Full Date/Time</em></td>
               <td>---</td>
               <td>---</td>
              </tr>
              <tr>
               <td><em>c</em></td>
               <td>ISO 8601 date (added in PHP 5)</td>
               <td>2004-02-12T15:19:21+00:00</td>
              </tr>
              <tr>
               <td><em>r</em></td>
               <td><a href="http://www.faqs.org/rfcs/rfc2822" class="link external">&raquo;&nbsp;RFC 2822</a> formatted date</td>
               <td>Example: <em>Thu, 21 Dec 2000 16:01:07 +0200</em></td>
              </tr>
              <tr>
               <td><em>U</em></td>
               <td>Seconds since the Unix Epoch (January 1 1970 00:00:00 GMT)</td>
               <td>See also <span class="function"><a href="https://www.php.net/manual/en/function.time.php" class="function">time()</a></span></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">Links</h2>
        </div>
        <div class="col-md-12">
          <button class="btn primary" onclick="window.location = '/time?mode=countup&time='+Math.floor((new Date).getTime()/1000)+'&unit=minute&digit=1'">Countup now</button>
        </div>
      </div>
    </div>
  </div>
</body>

</html>
