<!DOCTYPE html>
<html onclick="Core.Window.toggleFullscreen()">
<head>
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <link rel="stylesheet" href="style.css">
  <script src="script.js"></script>
  <title id="title">Time</title>
</head>
<body class="main" id="main" onload="Core.Window.setTitle('Time'); Core.Window.setProtocol('https:'); init();">
  <div class="box" id="box">
    <p class="text" id="text" onclick="copyElement(this)"></p>
  </div>
</body>
