<!DOCTYPE html>
<html>

<head>
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <link rel="stylesheet" href="style.css">
  <title>Micromouse</title>
</head>

<body onload="setTitle('Micromouse')">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>

<div class="body">
  <div class="p-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="">Micromouse</h1>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          Micromouse project for NYIT-IEEE-Manhattan.
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">Summary</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p class="lead">
            Micromouse competition is a robotic comptetion to navigate to the center of 16-by-16 maze using self-contained controller. <br>
            More information on rules can be found in <a href="http://sites.ieee.org/r1/files/2013/03/2013-Region-1-Micromouse-Competition-Rules.pdf">IEEE Region 1 Micromouse rules</a>.
          </p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p class="lead">
            Backtracking search in conjunction with uniform-cost search is used. <br>
            16-by-16 maze is represented as 31-by-31 2-dimensional byte array. <br>
            <a href="https://store.arduino.cc/usa/arduino-zero">Arduino Zero</a> is used as microcontroller.
          </p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p class="lead">
            More can be found in <a href="https://github.com/jerubball/Micromouse">GitHub page</a>. <br>
            For usage, please contact <a href="mailto:him@nyit.edu">him@nyit.edu</a> or <a href="mailto:ieeema@nyit.edu">ieeema@nyit.edu</a>.
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">Awards</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p class="lead">
            <ul>
              <li>2018 IEEE Region 1 student conference: 1st place as <b>HimBot</b>.</li>
              <li>2019 IEEE Region 1 student conference: 1st place as <b>Happy Saito</b>.</li>
            </ul>
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">Articles</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p class="lead">
            <ul>
              <li><a href='https://www.nyit.edu/box/features/top_honors_for_student_engineers'>Top Honors for Student Engineers</a></li>
              <li><a href='https://www.nyit.edu/box/features/nyit_students_make_a_major_showing_ieee_conference_competition'>NYIT Students Make a Major Showing at IEEE Conference Competition</a></li>
            </ul>
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">Gallery</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          
          <div class="carousel slide" data-ride="carousel" id="carousel" >
            <div class="carousel-inner">
              <div class="carousel-item active"> <img class="d-block img-fluid w-100" src="https://static.pingendo.com/cover-bubble-dark.svg">
                <div class="carousel-caption">
                  <h5 class="m-0">Carousel</h5>
                  <p>with controls</p>
                </div>
              </div>
              <div class="carousel-item"> <img class="d-block img-fluid w-100" src="https://static.pingendo.com/cover-bubble-light.svg">
                <div class="carousel-caption">
                  <h5 class="m-0">Carousel</h5>
                  <p>with controls</p>
                </div>
              </div>
              <div class="carousel-item"> <img class="d-block img-fluid w-100" src="https://static.pingendo.com/cover-moon.svg">
                <div class="carousel-caption">
                  <h5 class="m-0">Carousel</h5>
                  <p>with controls</p>
                </div>
              </div>
            </div> <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev"> <span class="carousel-control-prev-icon"></span> <span class="sr-only">Previous</span> </a> <a class="carousel-control-next" href="#carousel" role="button" data-slide="next"> <span class="carousel-control-next-icon"></span> <span class="sr-only">Next</span> </a>
          </div>
          
          
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">See it in action.</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="embed-responsive embed-responsive-custom">
            <iframe class="embed-responsive-item" src="https://drive.google.com/file/d/1yW__sXNssihpltDWMkp6VPI48O5ifR2I/preview" allowfullscreen></iframe>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

</body>

</html>
