<!DOCTYPE html>
<html>

<head>
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <title>Micromouse</title>
</head>

<body onload="setTitle('Micromouse')">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>

<div class="body">
  <div class="p-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="">Micromouse</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">See it in action.</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="embed-responsive">
            <iframe class="embed-responsive-item" src="https://drive.google.com/file/d/1yW__sXNssihpltDWMkp6VPI48O5ifR2I/preview" allowfullscreen></iframe>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

</body>

</html>
