<!DOCTYPE html>
<html>

<head>
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <link rel="stylesheet" href="style.css">
  <title>Micromouse</title>
</head>

<body onload="Core.Window.setTitle('Micromouse')">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>

<div class="body">
  <div class="p-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="">Micromouse</h1>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          Micromouse project for NYIT-IEEE-Manhattan.
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">Summary</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p class="lead">
            Micromouse competition is a robotic comptetion to navigate to the center of 16-by-16 maze using self-contained controller. <br>
            More information on rules can be found in <a href="http://sites.ieee.org/r1/files/2013/03/2013-Region-1-Micromouse-Competition-Rules.pdf">IEEE Region 1 Micromouse rules</a>.
          </p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p class="lead">
            Backtracking search in conjunction with uniform-cost search is used. <br>
            16-by-16 maze is represented as 31-by-31 2-dimensional byte array. <br>
            <a href="https://store.arduino.cc/usa/arduino-zero">Arduino Zero</a> is used as microcontroller.
          </p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p class="lead">
            More can be found in <a href="https://github.com/jerubball/Micromouse">GitHub page</a>. <br>
            For usage, please contact <a href="mailto:him@nyit.edu">him@nyit.edu</a> or <a href="mailto:ieeema@nyit.edu">ieeema@nyit.edu</a>.
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">Awards</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p class="lead">
            <ul>
              <li>2018 IEEE Region 1 student conference: 1st place as <b>HimBot</b>.</li>
              <li>2019 IEEE Region 1 student conference: 1st place as <b>Happy Saito</b>.</li>
            </ul>
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">Articles</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p class="lead">
            <ul>
              <li><a href='https://www.nyit.edu/box/features/top_honors_for_student_engineers'>Top Honors for Student Engineers</a></li>
              <li><a href='https://www.nyit.edu/box/features/nyit_students_make_a_major_showing_ieee_conference_competition'>NYIT Students Make a Major Showing at IEEE Conference Competition</a></li>
            </ul>
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">Gallery</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="carousel slide" data-ride="carousel" id="gallery-carousel" style="background:gray; height:75vh;">
            <div class="carousel-inner d-flex h-100 align-items-center">
              <div class="carousel-item position-relative active">
                <img class="d-block img-fluid" src="https://drive.google.com/uc?export=view&id=1V-j9V27WQvfwLnM_tfOOuxtgHh98Ard9">
                <div class="carousel-caption">
                  <p>HimBot in maze near center</p>
                </div>
              </div>
              <div class="carousel-item position-relative">
                <img class="d-block img-fluid" src="https://drive.google.com/uc?export=view&id=1rWP5gXhELdkSjwbR6IBy4Vzx6xweTHg8">
                <div class="carousel-caption">
                  <p>HimBot displayed in NYIT College of Engineering</p>
                </div>
              </div>
              <div class="carousel-item position-relative">
                <img class="d-block img-fluid" src="https://drive.google.com/uc?export=view&id=1Ttr5jXe6XKXUUG5kf74PWZbYDGLkPQQG">
                <div class="carousel-caption">
                  <p>Full Maze 2018</p>
                </div>
              </div>
              <div class="carousel-item position-relative">
                <img class="d-block img-fluid" src="https://drive.google.com/uc?export=view&id=1vF5juCXMOS_UX2H32XqOk43-SBqWlsYy">
                <div class="carousel-caption">
                  <p>First place award 2018</p>
                </div>
              </div>
              <!--
              <div class="carousel-item">
                <img class="d-block img-fluid" src="https://drive.google.com/uc?export=view&id=">
                <div class="carousel-caption">
                  <p></p>
                </div>
              </div>
              -->
            </div>
            <a class="carousel-control-prev" href="#gallery-carousel" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#gallery-carousel" role="button" data-slide="next">
              <span class="carousel-control-next-icon"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
          
          
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">See it in action.</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <!--
          <video controls>
            <source src="https://drive.google.com/a/nyit.edu/uc?export=download&id=1VG6LePh0gCvtQXczKD2BE5PWAPLD_qrD">
          </video>
          -->
          <div class="embed-responsive embed-responsive-custom">
            <iframe class="embed-responsive-item" src="https://drive.google.com/file/d/1yW__sXNssihpltDWMkp6VPI48O5ifR2I/preview" allowfullscreen></iframe>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

</body>

</html>
