<!DOCTYPE html>
<html>

<?php
  $location = $_SERVER['DOCUMENT_ROOT'].urldecode($_SERVER['REQUEST_URI']);
  if (!is_dir($location)) {
    $location = dirname($location);
  }
  $name = str_replace($_SERVER['DOCUMENT_ROOT'], '', $location);
  if ($name[-1] !== '/') {
    $name .= '/';
  }
  while (strpos($name, '//') !== false) {
    $name = str_replace('//', '/', $name);
  }
  chdir($location);
?>

<head>
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <title>Index of <?php echo $name; ?></title>
</head>

<body onload="Core.Window.setTitle('Index of <?php echo $name; ?>')">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>

<?php
  if ($dir = opendir('.')) {
    $table = array();
    $finfo = finfo_open(FILEINFO_MIME);
    while ($item = readdir($dir)) {
      if ($item[0] !== '.') {
        $entry = array();
        $entry['dir'] = is_dir($item);
        $entry['name'] = $item;
        $entry['type'] = filetype($item);
        $entry['mime'] = mime_content_type($item);
        $entry['title'] = finfo_file($finfo, $item);
        $entry['modified'] = filemtime($item);
        $entry['size'] = $entry['dir'] ? '-' : filesize($item);
        $table[] = $entry;
      }
    }
    closedir($dir);
    uasort($table, function($a, $b) {
      return strnatcasecmp($a['name'], $b['name']);
    });
  }
  function format_name($entry) {
    return $entry['dir'] ? $entry['name'].'/' : $entry['name'];
  }
  function format_type($entry) {
    return $entry['mime'];
  }
  function format_title($entry) {
    return $entry['type'].'; mime='.$entry['title'];
  }
  function format_modified($entry) {
    return date('M d Y, g:i:s a', $entry['modified']);
  }
  function format_size($entry) {
    if (is_numeric($entry['size'])) {
      $value = intval($entry['size']);
      $factor = 0;
      while ($value >= 1000) {
        $value /= 1024;
        $factor++;
      }
      $prefix = [' B', ' KiB', ' MiB', ' GiB', ' TiB', ' PiB', ' EiB'];
      if ($factor == 0) {
        return $value.$prefix[$factor];
      } else {
        return sprintf('%.1f', $value).$prefix[$factor];
      }
    } else {
      return $entry['size'];
    }
  }
?>

<div class="body">
  <div class="p-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="">Index of <?php echo $name; ?></h1>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
<?php
  if (!isset($table)) {
?>
          <p class="lead">
            Directory can not be accessed.
          </p>
<?php
  } else {
?>
          <table class="table sortable" id="table">
            <thead class="thead-light">
              <tr>
                <th scope="col" onclick="Core.Util.sortTable(this);" class="asc sorted">Name <i class="sort fa fa-sort-up"></i> <i class="sort fa fa-sort-down"></i></th>
                <th scope="col" onclick="Core.Util.sortTable(this);" class="asc">Type <i class="sort fa fa-sort-up"></i> <i class="sort fa fa-sort-down"></i></th>
                <th scope="col" onclick="Core.Util.sortTable(this);" class="asc">Modified <i class="sort fa fa-sort-up"></i> <i class="sort fa fa-sort-down"></i></th>
                <th scope="col" onclick="Core.Util.sortTable(this);" class="asc">Size <i class="sort fa fa-sort-up"></i> <i class="sort fa fa-sort-down"></i></th>
              </tr>
            </thead>
            <tbody>
                <th scope="row" data-sort="0"><a href="./..">../</a></th>
                <td data-sort="-"></td>
                <td data-sort="-"></td>
                <td data-sort="-"></td>
            </tbody>
            <tbody>
<?php
    $index = 0;
    foreach ($table as $entry) {
?>
              <tr>
                <th scope="row" data-sort="<?php echo ++$index; ?>"><a href="./<?php echo $entry['name']; ?>"><?php echo format_name($entry); ?></a></th>
                <td data-sort="<?php echo $entry['mime']; ?>" title="<?php echo format_title($entry); ?>"><?php echo format_type($entry); ?></td>
                <td data-sort="<?php echo $entry['modified']; ?>"><?php echo format_modified($entry); ?></td>
                <td data-sort="<?php echo $entry['size']; ?>"><?php echo format_size($entry); ?></td>
              </tr>
<?php
    }
?>
            </tbody>
          </table>
<?php
  }
?>
        </div>
      </div>
    </div>
  </div>
</div>

</body>

</html>

<?php
/*
  exec('ls -alF .', $output);
  exec('ls -1 --group-directories-first', $output);
  foreach ($output as $item) {
    $line = exec('file '.$item);
  }
  $output = scandir('.');
  natcasesort($list);
  $sort = $_GET['sort'];
  $desc = isset($_GET['desc']) ? -1 : 1;
  switch($sort) {
    case 'type':
      $func = function($a, $b) {
        return $desc * strnatcasecmp($a['mime'], $b['mime']);
      };
      break;
    default:
      $func = function($a, $b) {
        return $desc * strnatcasecmp($a['name'], $b['name']);
      };
      break;
  }
*/
?>
