<?php
  $code = isset($_GET["code"]) ? $_GET["code"] : $code = "";
  switch ($code) {
    case "100":
      $status = $code." Continue";
      $style = "text-info";
      break;
    case "101":
      $status = $code." Switching Protocols";
      $style = "text-info";
      break;
    case "102":
      $status = $code." Processing";
      $style = "text-info";
      break;
    case "103":
      $status = $code." Early Hints";
      $style = "text-info";
      break;
    case "200":
      $status = $code." OK";
      $style = "text-success";
      break;
    case "201":
      $status = $code." Created";
      $style = "text-success";
      break;
    case "202":
      $status = $code." Accepted";
      $style = "text-success";
      break;
    case "203":
      $status = $code." Non-Authoritative Information";
      $style = "text-success";
      break;
    case "204":
      $status = $code." No Content";
      $style = "text-success";
      break;
    case "205":
      $status = $code." Reset Content";
      $style = "text-success";
      break;
    case "206":
      $status = $code." Partial Content";
      $style = "text-success";
      break;
    case "207":
      $status = $code." Multi-Status";
      $style = "text-success";
      break;
    case "208":
      $status = $code." Already Reported";
      $style = "text-success";
      break;
    case "218":
      $status = $code." This is fine";
      $style = "text-success";
      break;
    case "226":
      $status = $code." IM Used";
      $style = "text-success";
      break;
    case "300":
      $status = $code." Multiple Choices";
      $style = "text-warning";
      break;
    case "301":
      $status = $code." Moved Permanently";
      $style = "text-warning";
      break;
    case "302":
      $status = $code." Found";
      $style = "text-warning";
      break;
    case "303":
      $status = $code." See Other";
      $style = "text-warning";
      break;
    case "304":
      $status = $code." Not Modified";
      $style = "text-warning";
      break;
    case "305":
      $status = $code." Use Proxy";
      $style = "text-warning";
      break;
    case "306":
      $status = $code." Switch Proxy";
      $style = "text-warning";
      break;
    case "307":
      $status = $code." Temporary Redirect";
      $style = "text-warning";
      break;
    case "308":
      $status = $code." Permanent Redirect";
      $style = "text-warning";
      break;
    case "400":
      $status = $code." Bad Request";
      $style = "text-danger";
      break;
    case "401":
      $status = $code." Unauthorized";
      $style = "text-danger";
      break;
    case "402":
      $status = $code." Payment Required";
      $style = "text-danger";
      break;
    case "403":
      $status = $code." Forbidden";
      $style = "text-danger";
      break;
    case "404":
      $status = $code." Not Found";
      $style = "text-danger";
      break;
    case "405":
      $status = $code." Method Not Allowed";
      $style = "text-danger";
      break;
    case "406":
      $status = $code." Not Acceptable";
      $style = "text-danger";
      break;
    case "407":
      $status = $code." Proxy Authentication Required";
      $style = "text-danger";
      break;
    case "408":
      $status = $code." Request Timeout";
      $style = "text-danger";
      break;
    case "409":
      $status = $code." Conflict";
      $style = "text-danger";
      break;
    case "410":
      $status = $code." Gone";
      $style = "text-danger";
      break;
    case "411":
      $status = $code." Length Required";
      $style = "text-danger";
      break;
    case "412":
      $status = $code." Precondition Failed";
      $style = "text-danger";
      break;
    case "413":
      $status = $code." Payload Too Large";
      $style = "text-danger";
      break;
    case "414":
      $status = $code." URI Too Long";
      $style = "text-danger";
      break;
    case "415":
      $status = $code." Unsupported Media Type";
      $style = "text-danger";
      break;
    case "416":
      $status = $code." Range Not Satisfiable";
      $style = "text-danger";
      break;
    case "417":
      $status = $code." Expectation Failed";
      $style = "text-danger";
      break;
    case "418":
      $status = $code." I'm a teapot";
      $style = "text-muted";
      break;
    case "421":
      $status = $code." Misdirected Request";
      $style = "text-danger";
      break;
    case "422":
      $status = $code." Unprocessable Entity";
      $style = "text-danger";
      break;
    case "423":
      $status = $code." Locked";
      $style = "text-danger";
      break;
    case "424":
      $status = $code." Failed Dependency";
      $style = "text-danger";
      break;
    case "426":
      $status = $code." Upgrade Required";
      $style = "text-danger";
      break;
    case "428":
      $status = $code." Precondition Required";
      $style = "text-danger";
      break;
    case "429":
      $status = $code." Too Many Requests";
      $style = "text-danger";
      break;
    case "431":
      $status = $code." Request Header Fields Too Large";
      $style = "text-danger";
      break;
    case "451":
      $status = $code." Unavailable For Legal Reasons";
      $style = "text-danger";
      break;
    case "500":
      $status = $code." Internal Server Error";
      $style = "text-danger";
      break;
    case "501":
      $status = $code." Not Implemented";
      $style = "text-danger";
      break;
    case "502":
      $status = $code." Bad Gateway";
      $style = "text-danger";
      break;
    case "503":
      $status = $code." Service Unavailable";
      $style = "text-danger";
      break;
    case "504":
      $status = $code." Gateway Timeout";
      $style = "text-danger";
      break;
    case "505":
      $status = $code." HTTP Version Not Supported";
      $style = "text-danger";
      break;
    case "506":
      $status = $code." Variant Also Negotiates";
      $style = "text-danger";
      break;
    case "507":
      $status = $code." Insufficient Storage";
      $style = "text-danger";
      break;
    case "508":
      $status = $code." Loop Detected";
      $style = "text-danger";
      break;
    case "509":
      $status = $code." Bandwidth Limit Exceeded";
      $style = "text-danger";
      break;
    case "510":
      $status = $code." Not Extended";
      $style = "text-danger";
      break;
    case "511":
      $status = $code." Network Authentication Required";
      $style = "text-danger";
      break;
    default:
      $status = "Error";
      $style = "text-primary";
      break;
  }
?>

<!DOCTYPE html>

<html>

<head>
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <title><?php echo $status; ?></title>
</head>

<body>
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>

<div class="body">
  <div class="p-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="display-4 font-italic <?php echo $style; ?>"><?php echo $status; ?></h1>
        </div>
      </div>
    </div>
  </div>
</div>

</body>

</html>
