<!DOCTYPE html>
<html>

<head>
  <meta name="google-site-verification" content="w1ig7tmYsNZOx3NG3Tl9Z7Qjhnr4SCSP5hj2PHQyp0Q" />
  <meta name="google-site-verification" content="rn-VacQBCbsa9skVcAD3Le8du7C8-PnkMYbjqFXm4o4" />
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <title>Landing Page</title>
</head>

<body onload="Core.Window.setTitle('Landing Page')">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>

<div class="body">
  <div class="p-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="display-3">Landing Page</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="">Go To's</h1>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <ul class="">
            <li>
              <h2 class="">
                <a href="/url/">Go to URL shortening &amp; redirect</a>
              </h2>
            </li>
            <li>
              <h2 class="">
                <a href="/time/">Go to Time application</a>
                <a href="/time/help">(Help topic)</a>
              </h2>
            </li>
            <li>
              <h2 class="">
                <a href="/scripts/">Go to Linux bash scripts</a>
              </h2>
            </li>
            <li>
              <h2 class="">
                <a href="/micromouse/">Go to Micromouse page</a>
              </h2>
            </li>
            <li>
              <h2 class="">
                <a href="/TrackingSystem/"><s>Go to Tracking System Application</s></a>
              </h2>
            </li>
            <li>
              <h2 class="">
                <a href="/rantadi/">Go to 랜타디 reference sheet</a>
              </h2>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="">SSL mode (http/https)</h1>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <ul class="">
            <li>
              <h2 class="">
                <a href="#" onclick="Core.Window.setProtocol('https:')">On</a> /
                <a href="#" onclick="Core.Window.setProtocol('http:')">Off</a> /
                <a href="#" onclick="Core.Window.toggleProtocol()">Toggle</a>
              </h2>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">Contact me</h2>
          <ul>
            <li>
              <a href="mailto:him.nyit@gmail.com">him.nyit@gmail.com</a>
            </li>
            <li>
              <a href="mailto:him@nyit.edu">him@nyit.edu</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

</body>

</html>
