<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/core.php');
?>
<!DOCTYPE html>
<html>

<head>
  <meta name="google-site-verification" content="w1ig7tmYsNZOx3NG3Tl9Z7Qjhnr4SCSP5hj2PHQyp0Q" />
  <meta name="google-site-verification" content="rn-VacQBCbsa9skVcAD3Le8du7C8-PnkMYbjqFXm4o4" />
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <title>Landing Page</title>
</head>

<body onload="Core.Window.setTitle('Landing Page')">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>

<div class="body">
  <div class="p-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="display-4">Landing Page</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">Go To's</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <ul class="">
            <li>
              <h3 class="">
                <a href="/url/">Go to URL shortening &amp; redirect</a>
              </h3>
            </li>
            <li>
              <h3 class="">
                <a href="/chat/">Go to Chat application</a> (<a href="/chat/?text">text</a>, <a href="/chat/?json">json</a>, <a href="/chat/?mysql">mysql</a>)
              </h3>
            </li>
            <li>
              <h3 class="">
                <a href="/time/">Go to Time application</a>
                <a href="/time/help">(Help topic)</a>
              </h3>
            </li>
            <li>
              <h3 class="">
                <a href="/wordclock/">Go to Word Clock application</a>
              </h3>
            </li>
            <li>
              <h3 class="">
                <a href="/mcsinglecommand/">Go to Minecraft single command generator</a>
              </h3>
            </li>
            <li>
              <h3 class="">
                <a href="/scripts/">Go to Linux bash scripts</a>
              </h3>
            </li>
            <li>
              <h3 class="">
                <a href="/micromouse/">Go to Micromouse page</a>
              </h3>
            </li>
            <li>
              <h3 class="">
                <a href="/TrackingSystem/"><s>Go to Tracking System Application</s></a>
              </h3>
            </li>
            <li>
              <h3 class="">
                <a href="/rantadi/">Go to 랜타디 reference sheet</a>
              </h3>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">SSL mode (http/https)</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <ul class="">
            <li>
              <h3 class="">
                <a href="#" onclick="Core.Window.setProtocol('https:')">On</a> /
                <a href="#" onclick="Core.Window.setProtocol('http:')">Off</a> /
                <a href="#" onclick="Core.Window.toggleProtocol()">Toggle</a>
              </h3>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h3 class="">In Development</h3>
          <ul>
            <li>
              <h5 class="">
                <a href="/color/">Color</a>
              </h5>
            </li>
            <li>
              <h5 class="">
                <a href="/editor/">Editor</a>
              </h5>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h3 class="">Others</h3>
          <ul>
            <li>
              <h4 class="">
                <a href="/about/">About</a>
              </h4>
            </li>
            <li>
              <h4 class="">
                <a href="/links/">Links</a>
              </h4>
            </li>
            <li>
              <h4 class="">
                <a href="/resume/">Resume</a>
              </h4>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h3 class="">Contact me</h3>
          <ul>
            <li>
              <h5 class="">
                <a href="mailto:him.nyit@gmail.com">him.nyit@gmail.com</a>
              </h5>
            </li>
            <li>
              <h5 class="">
                <a href="mailto:him@nyit.edu">him@nyit.edu</a>
              </h5>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

</body>

</html>
