<!DOCTYPE html>
<html>

<head>
  <meta name="google-site-verification" content="w1ig7tmYsNZOx3NG3Tl9Z7Qjhnr4SCSP5hj2PHQyp0Q" />
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <title>Links</title>
</head>

<body onload="setTitle('Links')">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>
  <div class="p-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="">Links</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">Internal</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <ul class="">
            <li>
              <h3 class="">
                <a href="#" onclick="setHostname('hasol.co', true)">hasol.co</a>
              </h3>
            </li>
            <li>
              <h3 class="">
                <a href="#" onclick="setHostname('him-nyit.ddns.net', true)">him-nyit.ddns.net</a>
              </h3>
            </li>
            <li>
              <h3 class="">
                <a href="#" onclick="setProtocol('ftp:', true)">FTP site</a>
              </h3>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div><div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">External</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <ul class="">
            <li>
              <h3 class="">
                <a href="http://sites.nyit.edu/him/home">Original Google Sites</a>
              </h3>
            </li>
            <li>
              <h3 class="">
                <a href="https://sites.google.com/nyit.edu/him/home">New Google Sites</a>
              </h3>
            </li>
            <li>
              <h3 class="">
                <a href="https://github.com/jerubball">GitHub</a>
              </h3>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</body>

</html>
