<!DOCTYPE html>
<html>

<head>
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <title>Links</title>
</head>

<body onload="Core.Window.setTitle('Links')">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>

<div class="body">
  <div class="p-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="">Links</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">Internal</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <ul class="">
            <li>
              <h3 class="">
                <a href="#" onclick="Core.Window.setHostname('hasol.co', true)">hasol.co</a>
              </h3>
            </li>
            <li>
              <h3 class="">
                <a href="#" onclick="Core.Window.setHostname('him-nyit.ddns.net', true)">him-nyit.ddns.net</a>
              </h3>
            </li>
            <li>
              <h3 class="">
                <a href="#" onclick="Core.Window.setHostname('nyit-him.ddns.net', true)">nyit-him.ddns.net</a>
              </h3>
            </li>
            <li>
              <h3 class="">
                <a href="#" onclick="Core.Window.setProtocol('ftp:', true)">FTP site</a>
              </h3>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">External</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <ul class="">
            <li>
              <h3 class="">
                <a href="http://sites.nyit.edu/him/home">Original Google Sites</a>
              </h3>
            </li>
            <li>
              <h3 class="">
                <a href="https://sites.google.com/nyit.edu/him/home">New Google Sites</a>
              </h3>
            </li>
            <li>
              <h3 class="">
                <a href="https://github.com/jerubball">GitHub</a>
              </h3>
            </li>
            <li>
              <h3 class="">
                <a href="https://jerubball.github.io/">GitHub.io page</a>
              </h3>
            </li>
            <li>
              <h3 class="">
                <a href="https://www.linkedin.com/in/hasol-im/">LinkedIn</a>
              </h3>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">Secrets</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <ul class="">
            <li>
              <a href="/about">About</a>
            </li>
            <li>
              <a href="/directory">Directory</a>
            </li>
            <li>
              <a href="/error">Error</a>
            </li>
            <li>
              <a href="/links">Links</a>
            </li>
            <li>
              <a href="/template">Template</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

</body>

</html>
