<!DOCTYPE html>
<html>

<head>
  <meta name="google-site-verification" content="w1ig7tmYsNZOx3NG3Tl9Z7Qjhnr4SCSP5hj2PHQyp0Q" />
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <title>template</title>
</head>

<body onload="setTitle('template')">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>

<div class="body">
  <div class="p-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="">Template</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">Content</h2>
        </div>
      </div>
    </div>
  </div>
</div>

</body>

</html>
