<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/core.php');
?>
<!DOCTYPE html>
<html>

<head>
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <link rel="stylesheet" href="style.css">
  <script src="script.js"></script>
  <title>Minecraft single command generator</title>
</head>

<body onload="Core.Window.setTitle('Minecraft single command generator')">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>

<div class="body">
  <div class="p-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="">Minecraft single command generator</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <textarea id="text" class="form-control text-editor" autocapitalize="none" autocomplete="off" spellcheck="false" placeholder="Enter commands/function"></textarea>
        </div>
      </div>
    </div>
  </div>
</div>

</body>

</html>
