<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/core.php');
?>
<!DOCTYPE html>
<html>

<head>
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <link rel="stylesheet" href="style.css">
  <script src="script.js"></script>
  <title>Resume</title>
</head>

<body onload="Core.Window.setTitle('Resume')">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>

<div class="body">
  <div class="p-4">
    <div class="container _title">
      <div class="row">
        <div class="col-md-12">
          <h1 class="" id="title">HIM&apos;s Resume</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="p-2">
    <div class="container _section" id="name">
      <div class="row pb-2">
        <div class="col-md-3">
          <div class="py-2 header sticky">
            <h2>Hasol&nbsp;Im</h2>
          </div>
        </div>
        <div class="col-md-9">
          <div class="container _content" id="name-content">
            <div class="row _items pt-2">
              <div class="col-lg-8">
                <h4><a href="mailto:him.nyit@gmail.com"><i class="fa fa-envelope-square" aria-hidden="true"></i> him.nyit@gmail.com</a></h4>
                <h4><a href="mailto:contact@hasol.co"><i class="fa fa-envelope-square" aria-hidden="true"></i> contact@hasol.co</a></h4>
                <h4><a href="https://www.linkedin.com/in/hasol-im/"><i class="fa fa-linkedin-square" aria-hidden="true"></i> LinkedIn Profile</a></h4>
                <h4><a href="https://github.com/jerubball"><i class="fa fa-github-square" aria-hidden="true"></i> GitHub Profile</a></h4>
              </div>
            </div>
            <div class="row _items pt-3">
              <div class="col-lg-8">
                <a class="collapse-control" href="#name-jump" data-bs-toggle="collapse" role="button" aria-controls="name-jump" aria-expanded="true">
                  <h4 class="d-inline-block">Jump down to ...</h4>
                  <i class="collapse-indicator fa fa-caret-down"></i>
                  <i class="collapse-indicator fa fa-caret-right"></i>
                </a>
              </div>
            </div>
            <div class="container collapse show" id="name-jump">
              <div class="row _item">
                <div class="col-12">
                  <h5><a href="#work"><i class="fa-solid fa-briefcase fa-fw"></i> Work Experience</a></h5>
                </div>
              </div>
              <div class="row _item">
                <div class="col-12">
                  <h5><a href="#education"><i class="fa-solid fa-graduation-cap fa-fw"></i> Education</a></h5>
                </div>
              </div>
              <div class="row _item">
                <div class="col-12">
                  <h5><a href="#skills"><i class="fa-solid fa-hammer fa-fw"></i> Skills</a></h5>
                </div>
              </div>
              <div class="row _item">
                <div class="col-12">
                  <h5><a href="#volunteer"><i class="fa-solid fa-hand-holding-heart fa-fw"></i> Volunteer Roles</a></h5>
                </div>
              </div>
              <div class="row _item">
                <div class="col-12">
                  <h5><a href="#activity"><i class="fa-solid fa-users fa-fw"></i> Activities</a></h5>
                </div>
              </div>
              <div class="row _item">
                <div class="col-12">
                  <h5><a href="#project"><i class="fa-solid fa-diagram-project fa-fw"></i> Projects</a></h5>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="p-2">
    <div class="container _section" id="work">
      <div class="row pb-2">
        <div class="col-md-3">
          <div class="py-2 header sticky">
            <h2>Work Experience</h2>
            <a class="pl-1" title="expand all" role="button" href="" onclick="return Script.collapseAll('work', false)"><i class="collapse-all fa fa-expand"></i></a>
            <a class="pl-1" title="collapse all" role="button" href="" onclick="return Script.collapseAll('work', true)"><i class="collapse-all fa fa-compress"></i></a>
            <a class="pl-1" title="jump to top" role="button" href="#title"><i class="collapse-all fa fa-level-up"></i></a>
          </div>
        </div>
        <div class="col-md-9">
          <div class="container _content" id="work-content">
            <div class="row _items pt-2 align-items-center">
              <div class="col-lg-8">
                <a class="collapse-control" href="#work-samsung" data-bs-toggle="collapse" role="button" aria-controls="work-samsung" aria-expanded="true">
                  <h3 class="d-inline-block">Samsung Electronics America</h3>
                  <i class="collapse-indicator fa fa-caret-down"></i>
                  <i class="collapse-indicator fa fa-caret-right"></i>
                </a>
              </div>
              <div class="col-lg-4 text-right text-lg-left">
                <h5>Oct.&nbsp;2021 - Present</h5>
              </div>
            </div>
            <div class="container collapse show _section_content_item pb-1" id="work-samsung">
              <div class="row _item">
                <div class="col-12">
                  <h5>Berkeley Heights, NJ</h5>
                </div>
              </div>
              <div class="row _items pt-2 pb-1">
                <div class="col-lg-8">
                  <h4><i class="fa-solid fa-gears"></i> Automation Engineer</h4>
                </div>
              </div>
              <div class="row _items pt-0">
                <div class="col-lg-8">
                  <h5>Contract vendor: Populus Group</h5>
                </div>
                <div class="col-lg-4 text-right text-lg-left">
                  <h6>Feb.&nbsp;2024 - Present</h6>
                </div>
              </div>
              <div class="row _items pt-0">
                <div class="col-lg-8">
                  <h5>Contract vendor: JND Inc.</h5>
                </div>
                <div class="col-lg-4 text-right text-lg-left">
                  <h6>Oct.&nbsp;2021 - Feb.&nbsp;2024</h6>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#work-samsung-summary" data-bs-toggle="collapse" role="button" aria-controls="work-samsung-summary" aria-expanded="true">
                    <h5 class="d-inline-block">Highlight</h5>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse show" id="work-samsung-summary">
                <div class="row _item">
                  <div class="col-12">
                    <h5>Created Robotic Process Automation (RPA) projects to save time on repetitive works.</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Maintained existing automation projects to support feature changes.</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Developed program for Chrome automation to extract and enter data on web systems.</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Developed program for Excel automation to generate statistical reports.</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Developed program for Jira/Confluence automation to perform business logic functions.</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Developed web portal to manage team&apos;s assets.</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Developed web portal to display summary dashboard of team&apos;s activity.</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Maintained company&apos;s remote testing infrastructure running on Linux/Ubuntu environment.</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Collaborated on team&apos;s network testing application.</h5>
                  </div>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#work-samsung-recognition" data-bs-toggle="collapse" role="button" aria-controls="work-samsung-recognition" aria-expanded="true">
                    <h5 class="d-inline-block">Recognitions</h5>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse show" id="work-samsung-recognition">
                <div class="row _item">
                  <div class="col-12">
                    <h5>RPA Best Practice 2022 - FOTA Report saved 800 hours annually</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>RPA Best Practice 2023 - Binary Uploader saved 800 hours annually</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>RPA Best Practice 2024 - Excel Automation saved 200 hours annually</h5>
                  </div>
                </div>
              </div>
            </div>
            <div class="row _items pt-3 align-items-center">
              <div class="col-lg-8">
                <a class="collapse-control" href="#work-nyit" data-bs-toggle="collapse" role="button" aria-controls="work-nyit" aria-expanded="true">
                  <h3 class="d-inline-block">New York Institute of Technology</h3>
                  <i class="collapse-indicator fa fa-caret-down"></i>
                  <i class="collapse-indicator fa fa-caret-right"></i>
                </a>
              </div>
              <div class="col-lg-4 text-right text-lg-left">
                <h5>Jul.&nbsp;2016 - Dec.&nbsp;2018</h5>
              </div>
            </div>
            <div class="container collapse show _section_content_item pb-1" id="work-nyit">
              <div class="row _item">
                <div class="col-12">
                  <h5>New York, NY</h5>
                </div>
              </div>
              <div class="row _items pt-2 pb-1">
                <div class="col-lg-8">
                  <h4><i class="fa-solid fa-chalkboard-user"></i> Tutor/Assistant</h4>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#work-nyit-summary" data-bs-toggle="collapse" role="button" aria-controls="work-nyit-summary" aria-expanded="true">
                    <h5 class="d-inline-block">Summary</h5>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse show" id="work-nyit-summary">
                <div class="row _item">
                  <div class="col-12">
                    <h5>Tutored in-campus for peer tutoring initiatives in multiple departments.</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Explained Computer Science courses and Mathematics courses.</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Helped students with clarifying important concepts and working on assignments.</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Maintained active email communication with students.</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Provided off-hour tutoring sessions through online messaging.</h5>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="p-2">
    <div class="container _section" id="education">
      <div class="row pb-2">
        <div class="col-md-3">
          <div class="py-2 header sticky">
            <h2>Education</h2>
            <a class="pl-1" title="expand all" role="button" href="" onclick="return Script.collapseAll('education', false)"><i class="collapse-all fa fa-expand"></i></a>
            <a class="pl-1" title="collapse all" role="button" href="" onclick="return Script.collapseAll('education', true)"><i class="collapse-all fa fa-compress"></i></a>
            <a class="pl-1" title="jump to top" role="button" href="#title"><i class="collapse-all fa fa-level-up"></i></a>
          </div>
        </div>
        <div class="col-md-9">
          <div class="container _content" id="education-content">
            <div class="row _items pt-2 align-items-center">
              <div class="col-lg-8">
                <a class="collapse-control" href="#education-nyit" data-bs-toggle="collapse" role="button" aria-controls="education-nyit" aria-expanded="true">
                  <h3 class="d-inline-block">New York Institute of Technology</h3>
                  <i class="collapse-indicator fa fa-caret-down"></i>
                  <i class="collapse-indicator fa fa-caret-right"></i>
                </a>
              </div>
              <div class="col-lg-4 text-right text-lg-left">
                <h5>Sep.&nbsp;2015 - Dec.&nbsp;2018</h5>
              </div>
            </div>
            <div class="container collapse show _section_content_item pb-1" id="education-nyit">
              <div class="row _item">
                <div class="col-12">
                  <h5>New York, NY</h5>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <h4>Bachelor&nbsp;of&nbsp;Science, Computer&nbsp;Science</h4>
                  <h5>Mathematics Minor</h5>
                </div>
                <div class="col-lg-4 text-right text-lg-left">
                  <h5>Dec.&nbsp;2018</h5>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#education-nyit-honors" data-bs-toggle="collapse" role="button" aria-controls="education-nyit-honors" aria-expanded="true">
                    <h4 class="d-inline-block">Honors</h4>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse show" id="education-nyit-honors">
                <div class="row _items">
                  <div class="col-lg-8">
                    <h5>summa&nbsp;cum&nbsp;laude</h5>
                  </div>
                  <div class="col-lg-4 text-right text-lg-left">
                    <h5>CGPA: 3.96/4.00</h5>
                  </div>
                </div>
                <div class="row _items">
                  <div class="col-lg-8">
                    <h5>Computer&nbsp;Science Faculty&nbsp;Award</h5>
                  </div>
                  <div class="col-lg-4 text-right text-lg-left">
                    <h6>May.&nbsp;2019</h6>
                  </div>
                </div>
                <div class="row _items">
                  <div class="col-lg-8">
                    <a class="collapse-control collapsed" href="#education-nyit-honors-presidential" data-bs-toggle="collapse" role="button" aria-controls="education-nyit-honors-presidential" aria-expanded="false">
                      <h5 class="d-inline-block">Presidential Honor List</h5>
                      <i class="collapse-indicator fa fa-caret-down"></i>
                      <i class="collapse-indicator fa fa-caret-right"></i>
                    </a>
                  </div>
                </div>
                <div class="container collapse" id="education-nyit-honors-presidential">
                  <div class="row _list pb-2">
                    <div class="col col-6 text-nowrap">
                      <span class="pb-1">Fall 2015</span>
                    </div>
                    <div class="col col-6 text-nowrap">
                      <span class="pb-1">Spring 2016</span>
                    </div>
                    <div class="col col-6 text-nowrap">
                      <span class="pb-1">Fall 2016</span>
                    </div>
                    <div class="col col-6 text-nowrap">
                      <span class="pb-1">Spring 2017</span>
                    </div>
                    <div class="col col-6 text-nowrap">
                      <span class="pb-1">Fall 2017</span>
                    </div>
                    <div class="col col-6 text-nowrap">
                      <span class="pb-1">Spring 2018</span>
                    </div>
                    <div class="col col-6 text-nowrap">
                      <span class="pb-1">Fall 2018</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#education-nyit-courses" data-bs-toggle="collapse" role="button" aria-controls="education-nyit-courses" aria-expanded="true">
                    <h4 class="d-inline-block">Courses</h4>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse show" id="education-nyit-courses">
                <div class="row _items pb-1">
                  <div class="col-lg-8">
                    <span>Senior Project - Smart Mirror Project</span>
                  </div>
                  <div class="col-lg-4 text-right text-lg-left">
                    <span>CSCI 455</span>
                  </div>
                </div>
                <div class="row _items pb-1">
                  <div class="col-lg-8">
                    <span>Big Data Management &amp, Analytics</span>
                  </div>
                  <div class="col-lg-4 text-right text-lg-left">
                    <span>CSCI 436</span>
                  </div>
                </div>
                <div class="row _items pb-1">
                  <div class="col-lg-8">
                    <span>Information Retrieval</span>
                  </div>
                  <div class="col-lg-4 text-right text-lg-left">
                    <span>CSCI 426</span>
                  </div>
                </div>
                <div class="row _items pb-1">
                  <div class="col-lg-8">
                    <span>Introduction to Data Mining</span>
                  </div>
                  <div class="col-lg-4 text-right text-lg-left">
                    <span>CSCI 415</span>
                  </div>
                </div>
                <div class="row _items pb-1">
                  <div class="col-lg-8">
                    <span>Introduction to Software Engineering</span>
                  </div>
                  <div class="col-lg-4 text-right text-lg-left">
                    <span>CSCI 380</span>
                  </div>
                </div>
                <div class="row _items pb-1">
                  <div class="col-lg-8">
                    <span>Artificial Intelligence I</span>
                  </div>
                  <div class="col-lg-4 text-right text-lg-left">
                    <span>CSCI 355</span>
                  </div>
                </div>
                <div class="row _items pb-1">
                  <div class="col-lg-8">
                    <span>Introduction to Network and Internet Security</span>
                  </div>
                  <div class="col-lg-4 text-right text-lg-left">
                    <span>CSCI 352</span>
                  </div>
                </div>
                <div class="row _items pb-1">
                  <div class="col-lg-8">
                    <span>Computer Networks</span>
                  </div>
                  <div class="col-lg-4 text-right text-lg-left">
                    <span>CSCI 345</span>
                  </div>
                </div>
                <div class="row _items pb-1">
                  <div class="col-lg-8">
                    <span>Design and Analysis of Algorithms</span>
                  </div>
                  <div class="col-lg-4 text-right text-lg-left">
                    <span>CSCI 335</span>
                  </div>
                </div>
                <div class="row _items pb-1">
                  <div class="col-lg-8">
                    <span>Operating Systems</span>
                  </div>
                  <div class="col-lg-4 text-right text-lg-left">
                    <span>CSCI 330</span>
                  </div>
                </div>
                <div class="row _items pb-1">
                  <div class="col-lg-8">
                    <span>Database Management</span>
                  </div>
                  <div class="col-lg-4 text-right text-lg-left">
                    <span>CSCI 300</span>
                  </div>
                </div>
                <div class="row _items pt-2">
                  <div class="col-lg-8">
                    <a class="collapse-control collapsed" href="#education-nyit-courses-csci" data-bs-toggle="collapse" role="button" aria-controls="education-nyit-courses-csci" aria-expanded="false">
                      <h5 class="d-inline-block">More Computer Science Courses</h5>
                      <i class="collapse-indicator fa fa-caret-down"></i>
                      <i class="collapse-indicator fa fa-caret-right"></i>
                    </a>
                  </div>
                </div>
                <div class="container collapse pb-2" id="education-nyit-courses-csci">
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>Programming Language Concepts</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>CSCI 318</span>
                    </div>
                  </div>
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>Theory of Computation</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>CSCI 312</span>
                    </div>
                  </div>
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>Probability and Statistics for Computer Science</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>CSCI 270</span>
                    </div>
                  </div>
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>Data Structures</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>CSCI 260</span>
                    </div>
                  </div>
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>Elements of Discrete Structures</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>CSCI 235</span>
                    </div>
                  </div>
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>Computer Programming II</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>CSCI 185</span>
                    </div>
                  </div>
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>Computer Organization and Architecture</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>CSCI 155</span>
                    </div>
                  </div>
                </div>
                <div class="row _items">
                  <div class="col-lg-8">
                    <a class="collapse-control collapsed" href="#education-nyit-courses-math" data-bs-toggle="collapse" role="button" aria-controls="education-nyit-courses-math" aria-expanded="false">
                      <h5 class="d-inline-block">Mathematics Courses</h5>
                      <i class="collapse-indicator fa fa-caret-down"></i>
                      <i class="collapse-indicator fa fa-caret-right"></i>
                    </a>
                  </div>
                </div>
                <div class="container collapse pb-2" id="education-nyit-courses-math">
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>Advanced Seminar</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>MATH 460</span>
                    </div>
                  </div>
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>Functions of a Complex Variable</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>MATH 360</span>
                    </div>
                  </div>
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>Differential Equations</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>MATH 320</span>
                    </div>
                  </div>
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>Linear Algebra</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>MATH 310</span>
                    </div>
                  </div>
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>Calculus III</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>MATH 260</span>
                    </div>
                  </div>
                </div>
                <div class="row _items">
                  <div class="col-lg-8">
                    <a class="collapse-control collapsed" href="#education-nyit-courses-other" data-bs-toggle="collapse" role="button" aria-controls="education-nyit-courses-other" aria-expanded="false">
                      <h5 class="d-inline-block">Other Courses</h5>
                      <i class="collapse-indicator fa fa-caret-down"></i>
                      <i class="collapse-indicator fa fa-caret-right"></i>
                    </a>
                  </div>
                </div>
                <div class="container collapse pb-2" id="education-nyit-courses-other">
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>Technology and Global Issues</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>IENG 400</span>
                    </div>
                  </div>
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>Modern New York</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>ICSS 306</span>
                    </div>
                  </div>
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>Ethics and Social Philosophy</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>ICPH 304</span>
                    </div>
                  </div>
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>Communication for Technical Professions</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>FCWR 304</span>
                    </div>
                  </div>
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>American Immigrant Literature</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>ICLT 301</span>
                    </div>
                  </div>
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>Writing II: Foundations of Research Writing for International Students</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>FCWR 161</span>
                    </div>
                  </div>
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>Writing I: Foundations of College Composition for International Students</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>FCWR 111</span>
                    </div>
                  </div>
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>Computer, Internet and Society</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>ETCS 108</span>
                    </div>
                  </div>
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>Career Discovery</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>ETCS 105</span>
                    </div>
                  </div>
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>Foundations of Speech Communication</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>FCSP 105</span>
                    </div>
                  </div>
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>Foundations of Scientific Process</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>FCSC 101</span>
                    </div>
                  </div>
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>Foundations of Inquiry</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>FCIQ 101</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="row _items pt-3 align-items-center">
              <div class="col-lg-8">
                <a class="collapse-control collapsed" href="#education-hewlett" data-bs-toggle="collapse" role="button" aria-controls="education-hewlett" aria-expanded="false">
                  <h3 class="d-inline-block">George W. Hewlett High School</h3>
                  <i class="collapse-indicator fa fa-caret-down"></i>
                  <i class="collapse-indicator fa fa-caret-right"></i>
                </a>
              </div>
              <div class="col-lg-4 text-right text-lg-left">
                <h5>Sep.&nbsp;2011 - Jun.&nbsp;2015</h5>
              </div>
            </div>
            <div class="container collapse _section_content_item pb-1" id="education-hewlett">
              <div class="row _item">
                <div class="col-12">
                  <h5>Hewlett, NY</h5>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#education-hewlett-diploma" data-bs-toggle="collapse" role="button" aria-controls="education-hewlett-diploma" aria-expanded="true">
                    <h4 class="d-inline-block">New York State Regents Diploma</h4>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
                <div class="col-lg-4 text-right text-lg-left">
                  <h5>Jun.&nbsp;2015</h5>
                </div>
              </div>
              <div class="container collapse show" id="education-hewlett-diploma">
                <div class="row _items">
                  <div class="col-lg-8">
                    <h5>Advanced Designation with Honors</h5>
                    <h5>Mastery in Math & Science</h5>
                  </div>
                  <div class="col-lg-4 text-right text-lg-left">
                    <h5>WGPA: 98.21/100.00</h5>
                  </div>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#education-hewlett-courses" data-bs-toggle="collapse" role="button" aria-controls="education-hewlett-courses" aria-expanded="true">
                    <h4 class="d-inline-block">Courses</h4>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse show" id="education-hewlett-courses">
                <div class="row _items">
                  <div class="col-lg-8">
                    <div class="row _item">
                      <div class="col-12">
                        <h5>College Board Advanced Placement</h5>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="container collapse show" id="education-hewlett-courses-ap">
                  <div class="row _list pb-2">
                    <div class="col col-12">
                      <span class="pb-1">Computer Science A</span>
                    </div>
                    <div class="col col-12">
                      <span class="pb-1">Calculus BC</span>
                    </div>
                    <div class="col col-12">
                      <span class="pb-1">Chemistry</span>
                    </div>
                    <div class="col col-12">
                      <span class="pb-1">Physics 1</span>
                    </div>
                  </div>
                </div>
                <div class="row _items">
                  <div class="col-lg-8">
                    <div class="row _item">
                      <div class="col-12">
                        <h5>Syracuse University Project Advance</h5>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="container collapse show pb-2" id="education-hewlett-courses-supa">
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>Economic Ideas and Issues</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>ECN 203</span>
                    </div>
                  </div>
                  <div class="row _items pb-1">
                    <div class="col-lg-8">
                      <span>An Introduction to the Analysis of Public Policy</span>
                    </div>
                    <div class="col-lg-4 text-right text-lg-left">
                      <span>PAF 101</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="p-2">
    <div class="container _section" id="skills">
      <div class="row pb-2">
        <div class="col-md-3">
          <div class="py-2 header sticky">
            <h2>Skills</h2>
            <a class="pl-1" title="expand all" role="button" href="" onclick="return Script.collapseAll('skills', false)"><i class="collapse-all fa fa-expand"></i></a>
            <a class="pl-1" title="collapse all" role="button" href="" onclick="return Script.collapseAll('skills', true)"><i class="collapse-all fa fa-compress"></i></a>
            <a class="pl-1" title="jump to top" role="button" href="#title"><i class="collapse-all fa fa-level-up"></i></a>
          </div>
        </div>
        <div class="col-md-9">
          <div class="container _content" id="skills-content">
            <div class="row _items pt-2">
              <div class="col-lg-8">
                <a class="collapse-control" href="#skills-cs" data-bs-toggle="collapse" role="button" aria-controls="skills-cs" aria-expanded="true">
                  <h3 class="d-inline-block">Computer Science</h3>
                  <i class="collapse-indicator fa fa-caret-down"></i>
                  <i class="collapse-indicator fa fa-caret-right"></i>
                </a>
              </div>
            </div>
            <div class="container collapse show _section_content_item pb-1" id="skills-cs">
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#skills-cs-language" data-bs-toggle="collapse" role="button" aria-controls="skills-cs-language" aria-expanded="true">
                    <h4 class="d-inline-block">Programming Language</h4>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse show" id="skills-cs-language">
                <div class="row _item">
                  <div class="col-12">
                    <h5><i class="fa-brands fa-python"></i> <b>Python3</b></h5>
                  </div>
                </div>
                <div class="container collapse show" id="skills-cs-language-python">
                  <div class="row _list pb-2">
                    <div class="col flex-grow-0 text-nowrap" style="flex-basis:11em;">
                      <span class="pb-1">atlassian-python-api</span>
                    </div>
                    <div class="col flex-grow-0 text-nowrap" style="flex-basis:11em;">
                      <span class="pb-1">beautifulsoup4</span>
                    </div>
                    <div class="col flex-grow-0 text-nowrap" style="flex-basis:11em;">
                      <span class="pb-1">matplotlib</span>
                    </div>
                    <div class="col flex-grow-0 text-nowrap" style="flex-basis:11em;">
                      <span class="pb-1">psycopg</span>
                    </div>
                    <div class="col flex-grow-0 text-nowrap" style="flex-basis:11em;">
                      <span class="pb-1">pyodbc</span>
                    </div>
                    <div class="col flex-grow-0 text-nowrap" style="flex-basis:11em;">
                      <span class="pb-1">pyotp</span>
                    </div>
                    <div class="col flex-grow-0 text-nowrap" style="flex-basis:11em;">
                      <span class="pb-1">pywin32</span>
                    </div>
                    <div class="col flex-grow-0 text-nowrap" style="flex-basis:11em;">
                      <span class="pb-1">tk/ttk/ttkthemes</span>
                    </div>
                    <div class="col flex-grow-0 text-nowrap" style="flex-basis:11em;">
                      <span class="pb-1">xlsxwriter</span>
                    </div>
                    <div class="col flex-grow-0 text-nowrap" style="flex-basis:11em;">
                      <span class="pb-1">xlwings</span>
                    </div>
                    <div class="col flex-grow-0 text-nowrap" style="flex-basis:11em;">
                      <span class="pb-1">Django</span>
                    </div>
                    <div class="col flex-grow-0 text-nowrap" style="flex-basis:11em;">
                      <span class="pb-1">PySimpleGUI</span>
                    </div>
                    <div class="col flex-grow-0 text-nowrap" style="flex-basis:11em;">
                      <span class="pb-1">Scrapy</span>
                    </div>
                    <div class="col flex-grow-0 text-nowrap" style="flex-basis:11em;">
                      <span class="pb-1">Selenium</span>
                    </div>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5><i class="fa-brands fa-java"></i> Java 8</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>C23/C++23</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>VBA</h5>
                  </div>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#skills-cs-webdev" data-bs-toggle="collapse" role="button" aria-controls="skills-cs-webdev" aria-expanded="true">
                    <h4 class="d-inline-block">Full Stack Web Development</h4>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse show" id="skills-cs-webdev">
                <div class="row _item">
                  <div class="col-12">
                    <h5><i class="fa-brands fa-js"></i> <b>JavaScript/ES2021</b></h5>
                  </div>
                </div>
                <div class="container collapse show" id="skills-cs-webdev-js">
                  <div class="row _list pb-2">
                    <div class="col text-nowrap">
                      <span class="pb-1">fetch/async/await</span>
                    </div>
                    <div class="col text-nowrap">
                      <span class="pb-1">jQuery</span>
                    </div>
                    <div class="col text-nowrap">
                      <span class="pb-1">DataTables</span>
                    </div>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5><i class="fa-brands fa-php"></i> PHP 8.3</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5><i class="fa-brands fa-html5"></i> HTML5 / <i class="fa-brands fa-css3-alt"></i> CSS3</h5>
                  </div>
                </div>
                <div class="container collapse show" id="skills-cs-webdev-html-css">
                  <div class="row _list pb-2">
                    <div class="col text-nowrap">
                      <span class="pb-1">Bootstrap 5.2</span>
                    </div>
                    <div class="col text-nowrap">
                      <span class="pb-1">Font Awesome</span>
                    </div>
                    <div class="col text-nowrap">
                      <span class="pb-1">Atlassian User Interface</span>
                    </div>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Apache HTTPD 2.4</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>MySQL 8.4 / MariaDB 11.4</h5>
                  </div>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#skills-cs-sysadmin" data-bs-toggle="collapse" role="button" aria-controls="skills-cs-sysadmin" aria-expanded="true">
                    <h4 class="d-inline-block">System Administration</h4>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse show" id="skills-cs-sysadmin">
                <div class="row _item">
                  <div class="col-12">
                    <h5><i class="fa-brands fa-ubuntu"></i> Ubuntu 24.10 / <i class="fa-brands fa-linux"></i> Linux 6.11</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5><b>Bash Shell Script</b></h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>OpenSSH client, server, configuration, tunneling, and file transfer</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Network, router, firewall management, and port forwarding</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Git command line interface</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Domain management and Dynamic DNS configuration</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5><i class="fa-brands fa-windows"></i> Windows Systems</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Batch Script / PowerShell Script</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Registry Editor / Group Policy Settings</h5>
                  </div>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#skills-cs-dbmgmt" data-bs-toggle="collapse" role="button" aria-controls="skills-cs-dbmgmt" aria-expanded="true">
                    <h4 class="d-inline-block">Database Management</h4>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse show" id="skills-cs-dbmgmt">
                <div class="row _item">
                  <div class="col-12">
                    <h5>MySQL / MariaDB / PostgreSQL</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>System configuration</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>User management</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Schema creation</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>CRUD operations</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>MongoDB / SQLite</h5>
                  </div>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control collapsed" href="#skills-cs-editor" data-bs-toggle="collapse" role="button" aria-controls="skills-cs-editor" aria-expanded="false">
                    <h4 class="d-inline-block">Code Editors</h4>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse" id="skills-cs-editor">
                <div class="row _list pb-2">
                  <div class="col col-12">
                    <span class="pb-1">Visual Studio Code</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">IntelliJ IDEA / Android Studio</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Eclipse</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Notepad++</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">GNU nano</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="row _items pt-3">
              <div class="col-lg-8">
                <a class="collapse-control" href="#skills-technology" data-bs-toggle="collapse" role="button" aria-controls="skills-technology" aria-expanded="true">
                  <h3 class="d-inline-block">Technology</h3>
                  <i class="collapse-indicator fa fa-caret-down"></i>
                  <i class="collapse-indicator fa fa-caret-right"></i>
                </a>
              </div>
            </div>
            <div class="container collapse show _section_content_item pb-1" id="skills-technology">
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control collapsed" href="#skills-technology-office" data-bs-toggle="collapse" role="button" aria-controls="skills-technology-office" aria-expanded="false">
                    <h4 class="d-inline-block">Office Productivity</h4>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse" id="skills-technology-office">
                <div class="row _list pb-2">
                  <div class="col col-12">
                    <span class="pb-1">Microsoft Word</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Microsoft Excel</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Microsoft PowerPoint</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Adobe Photoshop</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">GNU Image Manipulator Program</span>
                  </div>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control collapsed" href="#skills-technology-electronics" data-bs-toggle="collapse" role="button" aria-controls="skills-technology-electronics" aria-expanded="false">
                    <h4 class="d-inline-block">Electronics</h4>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse" id="skills-technology-electronics">
                <div class="row _list pb-2">
                  <div class="col col-12">
                    <span class="pb-1">Cat5/5e/6 Cable Termination</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Soldering / Circuit Assembly</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Arduino / Breadboard</span>
                  </div>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control collapsed" href="#skills-technology-audio" data-bs-toggle="collapse" role="button" aria-controls="skills-technology-audio" aria-expanded="false">
                    <h4 class="d-inline-block">Live Sound System</h4>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse" id="skills-technology-audio">
                <div class="row _list pb-2">
                  <div class="col col-12">
                    <span class="pb-1">System configuration</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Analog and Digital mixer control</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Setup and teardown</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Cable management</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="row _items pt-3">
              <div class="col-lg-8">
                <a class="collapse-control" href="#skills-communication" data-bs-toggle="collapse" role="button" aria-controls="skills-communication" aria-expanded="true">
                  <h3 class="d-inline-block">Communication</h3>
                  <i class="collapse-indicator fa fa-caret-down"></i>
                  <i class="collapse-indicator fa fa-caret-right"></i>
                </a>
              </div>
            </div>
            <div class="container collapse show _section_content_item pb-1" id="skills-communication">
              <div class="row _items">
                <div class="col-lg-8">
                  <div class="row _item">
                    <div class="col-12">
                      <h5>Language</h5>
                    </div>
                  </div>
                </div>
              </div>
              <div class="container collapse show pb-2" id="skills-communication-language">
                <div class="row _items pb-1">
                  <div class="col-lg-8 col-5">
                    <span>Korean</span>
                  </div>
                  <div class="col-lg-4 text-right text-lg-left col-7">
                    <span>First language</span>
                  </div>
                </div>
                <div class="row _items pb-1">
                  <div class="col-lg-8 col-5">
                    <span>English</span>
                  </div>
                  <div class="col-lg-4 text-right text-lg-left col-7">
                    <span>Full proficiency</span>
                  </div>
                </div>
              </div>
              <div class="row _items">
                <div class="col-lg-8">
                  <div class="row _item">
                    <div class="col-12">
                      <h5>Speech</h5>
                    </div>
                  </div>
                </div>
              </div>
              <div class="container collapse show" id="skills-communication-speech">
                <div class="row _list pb-2">
                  <div class="col col-12">
                    <span class="pb-1">Public Speaking</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Presentation</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Teaching/Training</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="p-2">
    <div class="container _section" id="volunteer">
      <div class="row pb-2">
        <div class="col-md-3">
          <div class="py-2 header sticky">
            <h2>Volunteer Roles</h2>
            <a class="pl-1" title="expand all" role="button" href="" onclick="return Script.collapseAll('volunteer', false)"><i class="collapse-all fa fa-expand"></i></a>
            <a class="pl-1" title="collapse all" role="button" href="" onclick="return Script.collapseAll('volunteer', true)"><i class="collapse-all fa fa-compress"></i></a>
            <a class="pl-1" title="jump to top" role="button" href="#title"><i class="collapse-all fa fa-level-up"></i></a>
          </div>
        </div>
        <div class="col-md-9">
          <div class="container _content" id="volunteer-content">
            <div class="row _items pt-2 align-items-center">
              <div class="col-lg-8">
                <a class="collapse-control" href="#volunteer-church" data-bs-toggle="collapse" role="button" aria-controls="volunteer-church" aria-expanded="true">
                  <h3 class="d-inline-block">New Vision Korean Methodist Church</h3>
                  <i class="collapse-indicator fa fa-caret-down"></i>
                  <i class="collapse-indicator fa fa-caret-right"></i>
                </a>
              </div>
              <div class="col-lg-4 text-right text-lg-left">
                <h5>Feb.&nbsp;2011 - Present</h5>
              </div>
            </div>
            <div class="container collapse show _section_content_item pb-1" id="volunteer-church">
              <div class="row _item">
                <div class="col-12">
                  <h5>East Rockaway, NY</h5>
                </div>
              </div>
              <div class="row _items pt-2 pb-1">
                <div class="col-lg-8">
                  <h4>Technology Staff</h4>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#volunteer-church-summary" data-bs-toggle="collapse" role="button" aria-controls="volunteer-church-summary" aria-expanded="true">
                    <h5 class="d-inline-block">Summary</h5>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse show" id="volunteer-church-summary">
                <div class="row _list pb-2">
                  <div class="col col-12">
                    <span class="pb-1">Maintained organizational domain with associated website and email server.</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Configured network system of the church building to increase wi-fi coverage.</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Maintained shared network printer and other equipments.</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Managed soundboard for PA system to integrate with live streaming using OBS Studio.</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="row _items pt-3 align-items-center">
              <div class="col-lg-8">
                <a class="collapse-control" href="#volunteer-mission" data-bs-toggle="collapse" role="button" aria-controls="volunteer-mission" aria-expanded="true">
                  <h3 class="d-inline-block">ALE Mission - Futuro Lleno de Esperanza</h3>
                  <i class="collapse-indicator fa fa-caret-down"></i>
                  <i class="collapse-indicator fa fa-caret-right"></i>
                </a>
              </div>
              <div class="col-lg-4 text-right text-lg-left">
                <h5>May.&nbsp;2022 - Present</h5>
              </div>
            </div>
            <div class="container collapse show _section_content_item pb-1" id="volunteer-mission">
              <div class="row _item">
                <div class="col-12">
                  <h5>Union Village, NJ</h5>
                </div>
              </div>
              <div class="row _items pt-2 pb-1">
                <div class="col-lg-8">
                  <h4>Director of Technology</h4>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#volunteer-mission-summary" data-bs-toggle="collapse" role="button" aria-controls="volunteer-mission-summary" aria-expanded="true">
                    <h5 class="d-inline-block">Summary</h5>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse show" id="volunteer-mission-summary">
                <div class="row _list pb-2">
                  <div class="col col-12">
                    <span class="pb-1">Maintained organizational domain with associated website and email server.</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Deployed student laptops and tablets with selection of software for new learning environment.</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Organized team&apos;s Google Drive with project plans and meeting minutes.</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="p-2">
    <div class="container _section" id="activity">
      <div class="row pb-2">
        <div class="col-md-3">
          <div class="py-2 header sticky">
            <h2>Activities</h2>
            <a class="pl-1" title="expand all" role="button" href="" onclick="return Script.collapseAll('activity', false)"><i class="collapse-all fa fa-expand"></i></a>
            <a class="pl-1" title="collapse all" role="button" href="" onclick="return Script.collapseAll('activity', true)"><i class="collapse-all fa fa-compress"></i></a>
            <a class="pl-1" title="jump to top" role="button" href="#title"><i class="collapse-all fa fa-level-up"></i></a>
          </div>
        </div>
        <div class="col-md-9">
          <div class="container _content" id="activity-content">
            <div class="row _items pt-2 align-items-center">
              <div class="col-lg-8">
                <a class="collapse-control" href="#activity-ieee" data-bs-toggle="collapse" role="button" aria-controls="activity-ieee" aria-expanded="true">
                  <h3 class="d-inline-block">Institute of Electrical and Electronics Engineers</h3>
                  <i class="collapse-indicator fa fa-caret-down"></i>
                  <i class="collapse-indicator fa fa-caret-right"></i>
                </a>
              </div>
              <div class="col-lg-4 text-right text-lg-left">
                <h5>Feb.&nbsp;2018 - May.&nbsp;2019</h5>
              </div>
            </div>
            <div class="container collapse show _section_content_item pb-1" id="activity-ieee">
              <div class="row _item">
                <div class="col-12">
                  <h5>NYIT Chapter, New York, NY</h5>
                </div>
              </div>
              <div class="row _items pt-2 pb-1">
                <div class="col-lg-8">
                  <h4>SysAdmin for United Engineering</h4>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#activity-ieee-summary" data-bs-toggle="collapse" role="button" aria-controls="activity-ieee-summary" aria-expanded="true">
                    <h5 class="d-inline-block">Summary</h5>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse show" id="activity-ieee-summary">
                <div class="row _list pb-2">
                  <div class="col col-12">
                    <span class="pb-1">Organizing shared club room</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Installed and managed Linux OS in computers</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Set up cluster computing, server hosting, remote access</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="row _items pt-3 align-items-center">
              <div class="col-lg-8">
                <a class="collapse-control" href="#activity-gk" data-bs-toggle="collapse" role="button" aria-controls="activity-gk" aria-expanded="true">
                  <h3 class="d-inline-block">Golden Key International Honour Society</h3>
                  <i class="collapse-indicator fa fa-caret-down"></i>
                  <i class="collapse-indicator fa fa-caret-right"></i>
                </a>
              </div>
              <div class="col-lg-4 text-right text-lg-left">
                <h5>Sep.&nbsp;2016 - Dec.&nbsp;2018</h5>
              </div>
            </div>
            <div class="container collapse show _section_content_item pb-1" id="activity-gk">
              <div class="row _item">
                <div class="col-12">
                  <h5>NYIT Chapter, New York, NY</h5>
                </div>
              </div>
              <div class="row _items pt-2 pb-1">
                <div class="col-lg-8">
                  <h4>President</h4>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#activity-gk-summary" data-bs-toggle="collapse" role="button" aria-controls="activity-gk-summary" aria-expanded="true">
                    <h5 class="d-inline-block">Summary</h5>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse show" id="activity-gk-summary">
                <div class="row _list pb-2">
                  <div class="col col-12">
                    <span class="pb-1">Coordinating events and sending email announcements</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Communicating with Chapter Advisor</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Maintaining student portal, member roster, and social media page</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="row _items pt-3 align-items-center">
              <div class="col-lg-8">
                <a class="collapse-control" href="#activity-innovo" data-bs-toggle="collapse" role="button" aria-controls="activity-innovo" aria-expanded="true">
                  <h3 class="d-inline-block">FIRST Tech Challenge Robotics Team</h3>
                  <i class="collapse-indicator fa fa-caret-down"></i>
                  <i class="collapse-indicator fa fa-caret-right"></i>
                </a>
              </div>
              <div class="col-lg-4 text-right text-lg-left">
                <h5>Sep.&nbsp;2011 - May.&nbsp;2015</h5>
              </div>
            </div>
            <div class="container collapse show _section_content_item pb-1" id="activity-innovo">
              <div class="row _item">
                <div class="col-12">
                  <h5>Hewlett Robotics Team, Hewlett, NY</h5>
                </div>
              </div>
              <div class="row _items pt-2 pb-1">
                <div class="col-lg-8">
                  <h4><i class="fa-regular fa-lightbulb"></i> Lead Programmer of Team 5477: Innovo</h4>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#activity-innovo-summary" data-bs-toggle="collapse" role="button" aria-controls="activity-innovo-summary" aria-expanded="true">
                    <h5 class="d-inline-block">Summary</h5>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse show" id="activity-innovo-summary">
                <div class="row _item">
                  <div class="col-12">
                    <h5>Programmed autonomous phase and manual control phase of the robot.</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Used RobotC programming language for Lego Mindstorm with TETRIX motor controllers.</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Documented weekly logs to the engineering notebook</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Hosted robotics competition events on-site, and volunteered to assist other events</h5>
                  </div>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#activity-innovo-awards" data-bs-toggle="collapse" role="button" aria-controls="activity-innovo-awards" aria-expanded="true">
                    <h5 class="d-inline-block">Awards</h5>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse show pb-2" id="activity-innovo-awards">
                <div class="row _items pb-1">
                  <div class="col-lg-8">
                    <span class="d-block">Hudson Valley Championship Winning Alliance</span>
                  </div>
                  <div class="col-lg-4 text-right text-lg-left">
                    <span>2011-12 season: Bowled Over!</span>
                  </div>
                </div>
                <div class="row _items pb-1">
                  <div class="col-lg-8">
                    <span class="d-block"><b>NYC Regional Tournament Champion Team</b></span>
                    <span class="d-block">NYC Regional Tournament Inspire Award Second Place</span>
                    <span class="d-block">NYC Regional Tournament Promote Award</span>
                  </div>
                  <div class="col-lg-4 text-right text-lg-left">
                    <span>2012-13 season: Ring It Up!</span>
                  </div>
                </div>
                <div class="row _items pb-1">
                  <div class="col-lg-8">
                    <span class="d-block">NYC Qualifier Winning Alliance</span>
                    <span class="d-block">NYC Qualifier Inspire Award Winning Team</span>
                  </div>
                  <div class="col-lg-4 text-right text-lg-left">
                    <span>2013-14 season: Block Party!</span>
                  </div>
                </div>
                <div class="row _items pb-1">
                  <div class="col-lg-8">
                    <span class="d-block">NYC/LI Syosset Qualifier Inspire Award Winning Team</span>
                  </div>
                  <div class="col-lg-4 text-right text-lg-left">
                    <span>2014-15 season: Cascade Effect</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="p-2">
    <div class="container _section" id="project">
      <div class="row pb-2">
        <div class="col-md-3">
          <div class="py-2 header sticky">
            <h2>Projects</h2>
            <a class="pl-1" title="expand all" role="button" href="" onclick="return Script.collapseAll('project', false)"><i class="collapse-all fa fa-expand"></i></a>
            <a class="pl-1" title="collapse all" role="button" href="" onclick="return Script.collapseAll('project', true)"><i class="collapse-all fa fa-compress"></i></a>
            <a class="pl-1" title="jump to top" role="button" href="#title"><i class="collapse-all fa fa-level-up"></i></a>
          </div>
        </div>
        <div class="col-md-9">
          <div class="container _content" id="project-content">
            <div class="row _items pt-2 align-items-center">
              <div class="col-lg-8">
                <a class="collapse-control" href="#project-website" data-bs-toggle="collapse" role="button" aria-controls="project-website" aria-expanded="true">
                  <h3 class="d-inline-block">This Website</h3>
                  <i class="collapse-indicator fa fa-caret-down"></i>
                  <i class="collapse-indicator fa fa-caret-right"></i>
                </a>
              </div>
              <div class="col-lg-4 text-right text-lg-left">
                <h5>Jun.&nbsp;2018 - Present</h5>
              </div>
            </div>
            <div class="container collapse show _section_content_item pb-1" id="project-website">
              <div class="row _item">
                <div class="col-12">
                  <h5><i class="fa-solid fa-globe"></i> Portfolio Website & Home Server</h5>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#project-website-summary" data-bs-toggle="collapse" role="button" aria-controls="project-website-summary" aria-expanded="true">
                    <h5 class="d-inline-block">Highlight</h5>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse show" id="project-website-summary">
                <div class="row _item">
                  <div class="col-12">
                    <h5>Created home server by working on every aspect of web hosting and system administration.</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Maintains dedicated Linux/Ubuntu machines with up-to-date softwares.</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Managed domain services provided by Cloudflare, and used ddclient for dynamic DNS service.</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Set up and configured Apache HTTP server, and used Certbot to install SSL certificates.</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Webpage is created using HTML, CSS, JavaScript, and PHP.</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Using GitHub to edit, save, and synchronize the website.</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>Configured home router to port forward network traffic.</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>SSH server is configured to be accessible from any remote place.</h5>
                  </div>
                </div>
                <div class="row _item">
                  <div class="col-12">
                    <h5>The website hosts frequently used files for personal tasks, and experimental pages for work environment.</h5>
                  </div>
                </div>
              </div>
            </div>
            <div class="row _items pt-3 align-items-center">
              <div class="col-lg-8">
                <a class="collapse-control" href="#project-healthcare" data-bs-toggle="collapse" role="button" aria-controls="project-healthcare" aria-expanded="true">
                  <h3 class="d-inline-block">Automatic Record Uploader for Healthcare Web Application</h3>
                  <i class="collapse-indicator fa fa-caret-down"></i>
                  <i class="collapse-indicator fa fa-caret-right"></i>
                </a>
              </div>
              <div class="col-lg-4 text-right text-lg-left">
                <h5>Nov.&nbsp;2023</h5>
              </div>
            </div>
            <div class="container collapse show _section_content_item pb-1" id="project-healthcare">
              <div class="row _item">
                <div class="col-12">
                  <h5>Personal project to assist Healthcare professional</h5>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#project-healthcare-summary" data-bs-toggle="collapse" role="button" aria-controls="project-healthcare-summary" aria-expanded="true">
                    <h5 class="d-inline-block">Summary</h5>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse show" id="project-healthcare-summary">
                <div class="row _list pb-2">
                  <div class="col col-12">
                    <span class="pb-1">Developed Python automation program to populate new record.</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Read patient data from existing Excel file, and enter the data into web portal using Chrome driver.</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">1 hour of manual labor is reduced to 15 minutes of automation.</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="row _items pt-3 align-items-center">
              <div class="col-lg-8">
                <a class="collapse-control" href="#project-micromouse" data-bs-toggle="collapse" role="button" aria-controls="project-micromouse" aria-expanded="true">
                  <h3 class="d-inline-block">IEEE Micromouse Project</h3>
                  <i class="collapse-indicator fa fa-caret-down"></i>
                  <i class="collapse-indicator fa fa-caret-right"></i>
                </a>
              </div>
              <div class="col-lg-4 text-right text-lg-left">
                <h5>Feb.&nbsp;2018 - Mar.&nbsp;2018</h5>
              </div>
            </div>
            <div class="container collapse show _section_content_item pb-1" id="project-micromouse">
              <div class="row _item">
                <div class="col-12">
                  <h5>Project for IEEE Student Conference</h5>
                </div>
              </div>
              <div class="row _item">
                <div class="col-12">
                  <h5><a href="/micromouse/"><i class="fa-solid fa-link"></i> Project Link</a></h5>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#project-micromouse-summary" data-bs-toggle="collapse" role="button" aria-controls="project-micromouse-summary" aria-expanded="true">
                    <h5 class="d-inline-block">Summary</h5>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse show" id="project-micromouse-summary">
                <div class="row _list pb-2">
                  <div class="col col-12">
                    <span class="pb-1">Used backtracking search and uniform-cost search to traverse maze.</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Utilized Arduino Zero with motor encoders and infrared (IR) sensors.</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Awarded First Place in Region 1 competition for two years.</span>
                  </div>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#project-micromouse-awards" data-bs-toggle="collapse" role="button" aria-controls="project-micromouse-awards" aria-expanded="true">
                    <h5 class="d-inline-block">Awards</h5>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse show pb-2" id="project-micromouse-awards">
                <div class="row _items pb-1">
                  <div class="col-lg-8">
                    <span>Region 1 Student Conference First Place</span>
                  </div>
                  <div class="col-lg-4 text-right text-lg-left">
                    <span>2018</span>
                  </div>
                </div>
                <div class="row _items pb-1">
                  <div class="col-lg-8">
                    <span>Region 1 Student Conference First Place</span>
                  </div>
                  <div class="col-lg-4 text-right text-lg-left">
                    <span>2019</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="row _items pt-3 align-items-center">
              <div class="col-lg-8">
                <a class="collapse-control" href="#project-mirror" data-bs-toggle="collapse" role="button" aria-controls="project-mirror" aria-expanded="true">
                  <h3 class="d-inline-block">Smart Mirror Project</h3>
                  <i class="collapse-indicator fa fa-caret-down"></i>
                  <i class="collapse-indicator fa fa-caret-right"></i>
                </a>
              </div>
              <div class="col-lg-4 text-right text-lg-left">
                <h5>Sep.&nbsp;2018 - Dec.&nbsp;2018</h5>
              </div>
            </div>
            <div class="container collapse show _section_content_item pb-1" id="project-mirror">
              <div class="row _item">
                <div class="col-12">
                  <h5>Coursework for Senior Project: CSCI 455</h5>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#project-mirror-summary" data-bs-toggle="collapse" role="button" aria-controls="project-mirror-summary" aria-expanded="true">
                    <h5 class="d-inline-block">Summary</h5>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse show" id="project-mirror-summary">
                <div class="row _list pb-2">
                  <div class="col col-12">
                    <span class="pb-1">Raspberry-Pi based smart display with mirror.</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Python-based program with Graphical User Interface.</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Displays useful information such as weather or train times.</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Integrates OpenCV face recognition for user detection.</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">GitHub repository was included in Arctic Code Vault.</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="row _items pt-3 align-items-center">
              <div class="col-lg-8">
                <a class="collapse-control" href="#project-search" data-bs-toggle="collapse" role="button" aria-controls="project-search" aria-expanded="true">
                  <h3 class="d-inline-block">Sports News Search Engine</h3>
                  <i class="collapse-indicator fa fa-caret-down"></i>
                  <i class="collapse-indicator fa fa-caret-right"></i>
                </a>
              </div>
              <div class="col-lg-4 text-right text-lg-left">
                <h5>Sep.&nbsp;2018 - Dec.&nbsp;2018</h5>
              </div>
            </div>
            <div class="container collapse show _section_content_item pb-1" id="project-search">
              <div class="row _item">
                <div class="col-12">
                  <h5>Coursework for Information Retrieval: CSCI 426</h5>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#project-search-summary" data-bs-toggle="collapse" role="button" aria-controls="project-search-summary" aria-expanded="true">
                    <h5 class="d-inline-block">Summary</h5>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse show" id="project-search-summary">
                <div class="row _list pb-2">
                  <div class="col col-12">
                    <span class="pb-1">Applied n-gram search of sports news article using TF-IDF method.</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Utilized Scrapy web crawlers to get news data.</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Created simple UI to interact with python via CGI</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="row _items pt-3 align-items-center">
              <div class="col-lg-8">
                <a class="collapse-control" href="#project-tracking" data-bs-toggle="collapse" role="button" aria-controls="project-tracking" aria-expanded="true">
                  <h3 class="d-inline-block">Child Location Tracking System</h3>
                  <i class="collapse-indicator fa fa-caret-down"></i>
                  <i class="collapse-indicator fa fa-caret-right"></i>
                </a>
              </div>
              <div class="col-lg-4 text-right text-lg-left">
                <h5>Mar.&nbsp;2018 - May.&nbsp;2018</h5>
              </div>
            </div>
            <div class="container collapse show _section_content_item pb-1" id="project-tracking">
              <div class="row _item">
                <div class="col-12">
                  <h5>Coursework for Intro to Software Engineering: CSCI 380</h5>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#project-tracking-summary" data-bs-toggle="collapse" role="button" aria-controls="project-tracking-summary" aria-expanded="true">
                    <h5 class="d-inline-block">Summary</h5>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse show" id="project-tracking-summary">
                <div class="row _list pb-2">
                  <div class="col col-12">
                    <span class="pb-1">Web Application for parents to see children&apos;s location</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Applied sound engineering practices to develop web application in a team.</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Used Bootstrap, JavaScript, and PHP for implementation.</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Deployed with Apache Server with SSL, MySQL Community Server, and GitHub.</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="row _items pt-3 align-items-center">
              <div class="col-lg-8">
                <a class="collapse-control" href="#project-puzzle" data-bs-toggle="collapse" role="button" aria-controls="project-puzzle" aria-expanded="true">
                  <h3 class="d-inline-block">8-Puzzle Solver</h3>
                  <i class="collapse-indicator fa fa-caret-down"></i>
                  <i class="collapse-indicator fa fa-caret-right"></i>
                </a>
              </div>
              <div class="col-lg-4 text-right text-lg-left">
                <h5>Feb.&nbsp;2017 - Apr.&nbsp;2017</h5>
              </div>
            </div>
            <div class="container collapse show _section_content_item pb-1" id="project-puzzle">
              <div class="row _item">
                <div class="col-12">
                  <h5>Coursework for Artificial Intelligence I: CSCI 355</h5>
                </div>
              </div>
              <div class="row _items pt-2">
                <div class="col-lg-8">
                  <a class="collapse-control" href="#project-puzzle-summary" data-bs-toggle="collapse" role="button" aria-controls="project-puzzle-summary" aria-expanded="true">
                    <h5 class="d-inline-block">Summary</h5>
                    <i class="collapse-indicator fa fa-caret-down"></i>
                    <i class="collapse-indicator fa fa-caret-right"></i>
                  </a>
                </div>
              </div>
              <div class="container collapse show" id="project-puzzle-summary">
                <div class="row _list pb-2">
                  <div class="col col-12">
                    <span class="pb-1">Used A* search algorithm to develop solution for 8-puzzle.</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Python-based program with command-line interface.</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Constructed different heuristic functions to study various efficiencies.</span>
                  </div>
                  <div class="col col-12">
                    <span class="pb-1">Program is modified to perform search on larger size puzzles.</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="p-2 py-3">
  </div>
</div>

</body>

</html>
