<?php
    require_once($_SERVER['DOCUMENT_ROOT'].'/core.php');
?>
<!DOCTYPE html>
<html>

<head>
<?php
    require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
    <link rel="stylesheet" href="style.css">
    <script src="script.js"></script>
    <title>Resume</title>
</head>

<body onload="Core.Window.setTitle('Resume')">
<?php
require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');

function append_children(array &$target, &$children = [], int $size = 1) {
    try {
        $merged = array_merge(...$children);
    } catch (TypeError $e) {
        // echo 'Caught exception: ', $e->getMessage(), "\n";
        $merged = $children;
    }
    $prefix = '';
    for ($i = 0; $i < $size; $i++) {
        $prefix .= '  ';
    }
    foreach ($merged as &$value) {
        $value = $prefix.$value;
    }
    unset($value);
    array_push($target, ...$merged);
}

function wrap_title(string $title, string $head) {
    return [
        '<div class="p-4">',
        '  <div class="container _title">',
        '    <div class="row">',
        '      <div class="col-md-12">',
        '        <'.$head.' class="" id="title">'.$title.'</'.$head.'>',
        '      </div>',
        '    </div>',
        '  </div>',
        '</div>',
    ];
}

function wrap_head(string $text, string $head, string $class = null) {
    return [
        '<'.$head.' class="'.($class ? $class : '').'">'.$text.'</'.$head.'>',
    ];
}

function wrap_section(string $title, string $head, string $sectionid = null, bool $collapse_button = true, bool $sticky = true, string $class1 = null, string $class2 = null, string $class3 = null, $children = []) {
    $result = [
        '<div class="p-2">',
        '  <div class="container _section">',
        '    <div class="row'.($class1 ? ' '.$class1 : '').'">',
        '      <div class="col-md-3'.($class2 ? ' '.$class2 : '').'">',
        '        <div class="py-2 header'.($sticky ? ' sticky' : '').'">',
        '          <'.$head.' class="">'.$title.'</'.$head.'>',
    ];
    if ($collapse_button) {
        array_push($result,
            '          <a class="pl-1" title="expand all" role="button" href="" onclick="return Script.collapseAll(\''.($sectionid ?: '').'\', false)"><i class="collapse-all fa fa-expand"></i></a>',
            '          <a class="pl-1" title="collapse all" role="button" href="" onclick="return Script.collapseAll(\''.($sectionid ?: '').'\', true)"><i class="collapse-all fa fa-compress"></i></a>',
            '          <a class="pl-1" title="jump to top" role="button" href="#title"><i class="collapse-all fa fa-level-up"></i></a>',
        );
    }
    array_push($result,
        '        </div>',
        '      </div>',
        '      <div class="col-md-9'.($class3 ? ' '.$class3 : '').'">',
        '        <div class="container _content"'.($sectionid ? ' id="'.$sectionid : '').'">',
    );
    append_children($result, $children, 5);
    array_push($result,
        '        </div>',
        '      </div>',
        '    </div>',
        '  </div>',
        '</div>',
    );
    return $result;
}

function wrap_collapse_control(string $title, string $head, bool $shown, string $target) {
    return [
        '<a class="collapse-control'.($shown ? '' : ' collapsed').'" href="#'.$target.'" data-bs-toggle="collapse" role="button" aria-controls="'.$target.'" aria-expanded="'.($shown ? 'true' : 'false').'">',
        '  <'.$head.' class="d-inline-block">'.$title.'</'.$head.'>',
        '  <i class="collapse-indicator fa fa-caret-down"></i>',
        '  <i class="collapse-indicator fa fa-caret-right"></i>',
        '</a>',
    ];
}

function wrap_container(string $containerid, string $class = null, bool $shown = false, $children = []) {
    $result = [
        '<div class="container collapse'.($shown ? ' show' : '').($class ? ' '.$class : '').'" id="'.$containerid.'">',
    ];
    append_children($result, $children, 1);
    array_push($result,
        '</div>',
    );
    return $result;
}

function wrap_div(string $class, string $divid = null, $children = []) {
    $result = [
        '<div class="'.$class.'"'.($divid ? ' id="'.$divid.'"' : '').'>',
    ];
    append_children($result, $children, 1);
    array_push($result,
        '</div>',
    );
    return $result;
}

function wrap_items(string $class1 = null, string $divid = null, string $class2 = null, string $class3 = null, $children1 = [], $children2 = []) {
    $result = [
        '<div class="row _items'.($class1 ? ' '.$class1 : '').'"'.($divid ? ' id="'.$divid.'"' : '').'>',
        '  <div class="col-lg-8'.($class2 ? ' '.$class2 : '').'">',
    ];
    append_children($result, $children1, 2);
    array_push($result,
        '  </div>',
    );
    if ($children2) {
        array_push($result,
            '  <div class="col-lg-4 text-right text-lg-left'.($class3 ? ' '.$class3 : '').'">',
        );
        append_children($result, $children2, 2);
        array_push($result,
            '  </div>',
        );
    }
    array_push($result,
        '</div>',
    );
    return $result;
}

function wrap_item_simple(string $text, string $head = 'h6') {
    return [
        '<div class="row _item">', 
        '  <div class="col-lg-12">', 
        '    '.wrap_head($text, $head)[0],
        '  </div>',
        '</div>',
    ];
}

function wrap_item_list(string $width = null, $children = []) {
    $result = [
        '<div class="row _list">'
    ];
    foreach ($children as &$item) {
        array_push($result,
            '  <div class="col"'.( $width ? ' style="flex: 0 0 '.$width.';"' : '').'>',
            '    <span>'.$item.'</span>',
            '  </div>',
        );
    }
    array_push($result,
        '</div>',
    );
    return $result;
}
?>

<div class="body">
<?php
// echo phpversion();
echo "  ";
echo implode("\n  ", array_merge(
    wrap_title('HIM&apos;s Resume', 'h1'),

    wrap_section('Hasol&nbsp;Im', 'h2', 'name', collapse_button: false, sticky: true, children: [
        wrap_items('pt-2', children1: [
            wrap_head('<a href="mailto:him.nyit@gmail.com"><i class="fa fa-envelope-square" aria-hidden="true"></i> him.nyit@gmail.com</a>', 'h4'),
            wrap_head('<a href="mailto:contact@hasol.co"><i class="fa fa-envelope-square" aria-hidden="true"></i> contact@hasol.co</a>', 'h4'),
            wrap_head('<a href="https://www.linkedin.com/in/hasol-im/"><i class="fa fa-linkedin-square" aria-hidden="true"></i> LinkedIn Profile</a>', 'h4'),
            wrap_head('<a href="https://github.com/jerubball"><i class="fa fa-github-square" aria-hidden="true"></i> GitHub Profile</a>', 'h4'),
        ]),
        wrap_items('pt-3', children1: [
            wrap_collapse_control('Jump down to ...', 'h4', shown: true, target: 'name-jump'),
        ]),
        wrap_container('name-jump', shown: true, children: [
            wrap_item_simple('<a href="#work"><i class="fa-solid fa-briefcase fa-fw"></i> Work Experience</a>', 'h5'),
            wrap_item_simple('<a href="#education"><i class="fa-solid fa-graduation-cap fa-fw"></i> Education</a>', 'h5'),
            wrap_item_simple('<a href="#skills"><i class="fa-solid fa-hammer fa-fw"></i> Skills</a>', 'h5'),
            wrap_item_simple('<a href="#volunteer"><i class="fa-solid fa-hand-holding-heart fa-fw"></i> Volunteer Roles</a>', 'h5'),
            wrap_item_simple('<a href="#activities"><i class="fa-solid fa-users fa-fw"></i> Activities</a>', 'h5'),
            wrap_item_simple('<a href="#projects"><i class="fa-solid fa-diagram-project fa-fw"></i> Projects</a>', 'h5'),
        ]),
    ]),

    wrap_section('Work Experience', 'h2', 'work', class1: 'pb-2', children: [
        wrap_items('pt-2', children1: [
            wrap_collapse_control('Samsung Electronics America', 'h3', shown: true, target: 'work-samsung'),
        ], children2: [
            wrap_head('Oct.&nbsp;2021 - Present', 'h5'),
        ]),
        wrap_container('work-samsung', class: 'pb-1', shown: true, children: [
            wrap_item_simple('Berkeley Heights, NJ', 'h5'),
            wrap_items('pt-2 pb-1', children1: [
                wrap_head('<i class="fa-solid fa-gears"></i> Automation Enginner', 'h4'),
            ]),
            wrap_items('pt-0', children1: [
                wrap_head('Contract vendor: Populus Group', 'h5'),
            ], children2: [
                wrap_head('Feb.&nbsp;2024 - Present', 'h6'),
            ]),
            wrap_items('pt-0', children1: [
                wrap_head('Contract vendor: JND Inc.', 'h5'),
            ], children2: [
                wrap_head('Oct.&nbsp;2021 - Feb.&nbsp;2024', 'h6'),
            ]),
            wrap_items('pt-2', children1: [
                wrap_collapse_control('Highlight', 'h5', shown: true, target: 'work-samsung-summary'),
            ]),
            wrap_container('work-samsung-summary', shown: true, children: [
                wrap_item_simple('Created computer automation projects to save time on repetitive works.', 'h5'),
                wrap_item_simple('Maintained existing automation projects to support feature changes.', 'h5'),
                wrap_item_simple('Developed program for Chrome automation to extract and enter data on web systems.', 'h5'),
                wrap_item_simple('Developed program for Excel automation to generate statistical reports.', 'h5'),
                wrap_item_simple('Developed program for Jira/Confluence automation to perform business logic functions.', 'h5'),
                wrap_item_simple('Developed web portal to manage team&apos;s assets.', 'h5'),
                wrap_item_simple('Developed web portal to display summary dashboard of team&apos;s activity.', 'h5'),
                wrap_item_simple('Maintained company&apos;s remote testing infrastructure running on Linux/Ubuntu environment.', 'h5'),
                wrap_item_simple('Collaborated on team&apos;s network testing application.', 'h5'),
            ]),
        ]),

        wrap_items('pt-3', children1: [
            wrap_collapse_control('New York Institute of Technology', 'h3', shown: true, target: 'work-nyit'),
        ], children2: [
            wrap_head('Jul.&nbsp;2016 - Dec.&nbsp;2018', 'h5'),
        ]),
        wrap_container('work-nyit', class: 'pb-1', shown: true, children: [
            wrap_item_simple('New York, NY', 'h5'),
            wrap_items('pt-2 pb-1', children1: [
                wrap_head('<i class="fa-solid fa-chalkboard-user"></i> Tutor/Assistant', 'h4'),
            ]),
            wrap_items('pt-2', children1: [
                wrap_collapse_control('Summary', 'h5', shown: true, target: 'work-nyit-summary'),
            ]),
            wrap_container('work-nyit-summary', shown: true, children: [
                wrap_item_simple('Tutored in-campus for peer tutoring initiatives in multiple departments.', 'h5'),
                wrap_item_simple('Explained Computer Science courses and Mathematics courses.', 'h5'),
                wrap_item_simple('Helped students with clarifying important concepts and working on assignments.', 'h5'),
                wrap_item_simple('Maintained active email communication with students.', 'h5'),
                wrap_item_simple('Provided off-hour tutoring sessions through online messaging.', 'h5'),
            ]),
        ]),
    ]),

    wrap_section('Education', 'h2', 'education', class1: 'pb-2', children: [
        wrap_items('pt-2', children1: [
            wrap_collapse_control('New York Institute of Technology', 'h3', shown: true, target: 'education-nyit'),
        ], children2: [
            wrap_head('Sep.&nbsp;2015 - Dec.&nbsp;2018', 'h5'),
        ]),
        wrap_container('education-nyit', class: 'pb-1', shown: true, children: [
            wrap_item_simple('New York, NY', 'h5'),
            wrap_items('pt-2', children1: [
                wrap_head('Bachelor&nbsp;of&nbsp;Science, Computer&nbsp;Science', 'h4'),
                wrap_head('Mathematics Minor', 'h5'),
            ], children2: [
                wrap_head('Dec.&nbsp;2018', 'h5'),
            ]),
            wrap_items('pt-2', children1: [
                wrap_collapse_control('Honors', 'h4', shown: true, target: 'education-nyit-honors'),
            ]),
            wrap_container('education-nyit-honors', shown: true, children: [
                wrap_items(children1: [
                    wrap_head('summa&nbsp;cum&nbsp;laude', 'h5'),
                ], children2: [
                    wrap_head('CGPA: 3.96/4.00', 'h5'),
                ]),
                wrap_items(children1: [
                    wrap_head('Computer&nbsp;Science Faculty&nbsp;Award', 'h5'),
                ], children2: [
                    wrap_head('May.&nbsp;2019', 'h6'),
                ]),
                wrap_items(children1: [
                    wrap_collapse_control('Presidential Honor List', 'h5', shown: false, target: 'education-nyit-honors-presidential'),
                ]),
                wrap_container('education-nyit-honors-presidential', children: [
                    wrap_item_simple('Fall 2015'),
                    wrap_item_simple('Spring 2016'),
                    wrap_item_simple('Fall 2016'),
                    wrap_item_simple('Spring 2017'),
                    wrap_item_simple('Fall 2017'),
                    wrap_item_simple('Spring 2018'),
                    wrap_item_simple('Fall 2018'),
                ]),
            ]),
            wrap_items('pt-2', children1: [
                wrap_collapse_control('Courses', 'h4', shown: true, target: 'education-nyit-courses'),
            ]),
            wrap_container('education-nyit-courses', shown: true, children: [
                wrap_items(children1: [
                    wrap_head('Senior Proejct', 'h5'),
                ], children2: [
                    wrap_head('CSCI 455', 'h6'),
                ]),
                wrap_items(children1: [
                    wrap_head('Big Data Management &amp, Analytics', 'h5'),
                ], children2: [
                    wrap_head('CSCI 436', 'h6'),
                ]),
                wrap_items(children1: [
                    wrap_head('Information Retrieval', 'h5'),
                ], children2: [
                    wrap_head('CSCI 426', 'h6'),
                ]),
                wrap_items(children1: [
                    wrap_head('Introduction to Data Mining', 'h5'),
                ], children2: [
                    wrap_head('CSCI 415', 'h6'),
                ]),
                wrap_items(children1: [
                    wrap_head('Introduction to Software Engineering', 'h5'),
                ], children2: [
                    wrap_head('CSCI 380', 'h6'),
                ]),
                wrap_items(children1: [
                    wrap_head('Artificial Intelligence I', 'h5'),
                ], children2: [
                    wrap_head('CSCI 355', 'h6'),
                ]),
                wrap_items(children1: [
                    wrap_head('Introduction to Network and Internet Security', 'h5'),
                ], children2: [
                    wrap_head('CSCI 352', 'h6'),
                ]),
                wrap_items(children1: [
                    wrap_head('Computer Networks', 'h5'),
                ], children2: [
                    wrap_head('CSCI 345', 'h6'),
                ]),
                wrap_items(children1: [
                    wrap_head('Design and Analysis of Algorithms', 'h5'),
                ], children2: [
                    wrap_head('CSCI 335', 'h6'),
                ]),
                wrap_items(children1: [
                    wrap_collapse_control('More Computer Science Courses', 'h5', shown: false, target: 'education-nyit-courses-csci'),
                ]),
                wrap_container('education-nyit-courses-csci', children: [
                    wrap_items(children1: [
                        wrap_head('Operating Systems', 'h6'),
                    ], children2: [
                        wrap_head('CSCI 330', 'h6'),
                    ]),
                    wrap_items(children1: [
                        wrap_head('Programming Language Concepts', 'h6'),
                    ], children2: [
                        wrap_head('CSCI 318', 'h6'),
                    ]),
                    wrap_items(children1: [
                        wrap_head('Theory of Computation', 'h6'),
                    ], children2: [
                        wrap_head('CSCI 312', 'h6'),
                    ]),
                    wrap_items(children1: [
                        wrap_head('Database Management', 'h6'),
                    ], children2: [
                        wrap_head('CSCI 300', 'h6'),
                    ]),
                    wrap_items(children1: [
                        wrap_head('Probability and Statistics for Computer Science', 'h6'),
                    ], children2: [
                        wrap_head('CSCI 270', 'h6'),
                    ]),
                    wrap_items(children1: [
                        wrap_head('Data Structures', 'h6'),
                    ], children2: [
                        wrap_head('CSCI 260', 'h6'),
                    ]),
                    wrap_items(children1: [
                        wrap_head('Elements of Discrete Structures', 'h6'),
                    ], children2: [
                        wrap_head('CSCI 235', 'h6'),
                    ]),
                    wrap_items(children1: [
                        wrap_head('Computer Programming II', 'h6'),
                    ], children2: [
                        wrap_head('CSCI 185', 'h6'),
                    ]),
                    wrap_items(children1: [
                        wrap_head('Computer Organization and Architecture', 'h6'),
                    ], children2: [
                        wrap_head('CSCI 155', 'h6'),
                    ]),
                ]),
                wrap_items(children1: [
                    wrap_collapse_control('Mathematics Courses', 'h5', shown: false, target: 'education-nyit-courses-math'),
                ]),
                wrap_container('education-nyit-courses-math', children: [
                    wrap_items(children1: [
                        wrap_head('Advanced Seminar', 'h6'),
                    ], children2: [
                        wrap_head('MATH 460', 'h6'),
                    ]),
                    wrap_items(children1: [
                        wrap_head('Functions of a Complex Variable', 'h6'),
                    ], children2: [
                        wrap_head('MATH 360', 'h6'),
                    ]),
                    wrap_items(children1: [
                        wrap_head('Differential Equations', 'h6'),
                    ], children2: [
                        wrap_head('MATH 320', 'h6'),
                    ]),
                    wrap_items(children1: [
                        wrap_head('Linear Algebra', 'h6'),
                    ], children2: [
                        wrap_head('MATH 310', 'h6'),
                    ]),
                    wrap_items(children1: [
                        wrap_head('Calculus III', 'h6'),
                    ], children2: [
                        wrap_head('MATH 260', 'h6'),
                    ]),
                ]),
                wrap_items(children1: [
                    wrap_collapse_control('Other Courses', 'h5', shown: false, target: 'education-nyit-courses-other'),
                ]),
                wrap_container('education-nyit-courses-other', children: [
                    wrap_items(children1: [
                        wrap_head('Technology and Global Issues', 'h6'),
                    ], children2: [
                        wrap_head('IENG 400', 'h6'),
                    ]),
                    wrap_items(children1: [
                        wrap_head('Modern New York', 'h6'),
                    ], children2: [
                        wrap_head('ICSS 306', 'h6'),
                    ]),
                    wrap_items(children1: [
                        wrap_head('Ethics and Social Philosophy', 'h6'),
                    ], children2: [
                        wrap_head('ICPH 304', 'h6'),
                    ]),
                    wrap_items(children1: [
                        wrap_head('Communication for Technical Professions', 'h6'),
                    ], children2: [
                        wrap_head('FCWR 304', 'h6'),
                    ]),
                    wrap_items(children1: [
                        wrap_head('American Immigrant Literature', 'h6'),
                    ], children2: [
                        wrap_head('ICLT 301', 'h6'),
                    ]),
                    wrap_items(children1: [
                        wrap_head('Writing II: Foundations of Research Writing for International Students', 'h6'),
                    ], children2: [
                        wrap_head('FCWR 161', 'h6'),
                    ]),
                    wrap_items(children1: [
                        wrap_head('Writing I: Foundations of College Composition for International Students', 'h6'),
                    ], children2: [
                        wrap_head('FCWR 111', 'h6'),
                    ]),
                    wrap_items(children1: [
                        wrap_head('Computer, Internet and Society', 'h6'),
                    ], children2: [
                        wrap_head('ETCS 108', 'h6'),
                    ]),
                    wrap_items(children1: [
                        wrap_head('Career Discovery', 'h6'),
                    ], children2: [
                        wrap_head('ETCS 105', 'h6'),
                    ]),
                    wrap_items(children1: [
                        wrap_head('Foundations of Speech Communication', 'h6'),
                    ], children2: [
                        wrap_head('FCSP 105', 'h6'),
                    ]),
                    wrap_items(children1: [
                        wrap_head('Foundations of Scientific Process', 'h6'),
                    ], children2: [
                        wrap_head('FCSC 101', 'h6'),
                    ]),
                    wrap_items(children1: [
                        wrap_head('Foundations of Inquiry', 'h6'),
                    ], children2: [
                        wrap_head('FCIQ 101', 'h6'),
                    ]),
                ]),
            ]),
        ]),

        wrap_items('pt-3', children1: [
            wrap_collapse_control('George W. Hewlett High School', 'h3', shown: false, target: 'education-hewlett'),
        ], children2: [
            wrap_head('Sep.&nbsp;2011 - Jun.&nbsp;2015', 'h5'),
        ]),
        wrap_container('education-hewlett', class: 'pb-1', children: [
            wrap_item_simple('Hewlett, NY', 'h5'),
            wrap_items('pt-2', children1: [
                wrap_collapse_control('New York State Regents Diploma', 'h4', shown: true, target: 'education-hewlett-diploma'),
            ], children2: [
                wrap_head('Jun.&nbsp;2015', 'h5'),
            ]),
            wrap_container('education-hewlett-diploma', shown: true, children: [
                wrap_items(children1: [
                    wrap_head('Advanced Designation with Honors', 'h5'),
                    wrap_head('Mastery in Math & Science', 'h5'),
                ], children2: [
                    wrap_head('WGPA: 98.21/100.00', 'h5'),
                ]),
            ]),
            wrap_items('pt-2', children1: [
                wrap_collapse_control('Courses', 'h4', shown: true, target: 'education-hewlett-courses'),
            ]),
            wrap_container('education-hewlett-courses', shown: true, children: [
                wrap_items(children1: [
                    // wrap_collapse_control('College Board Advanced Placement', 'h5', shown: true, target: 'education-hewlett-courses-ap'),
                    wrap_item_simple('College Board Advanced Placement', 'h5'),
                ]),
                wrap_container('education-hewlett-courses-ap', shown: true, children: [
                    wrap_item_simple('Computer Science A', 'h6'),
                    wrap_item_simple('Calculus BC', 'h6'),
                    wrap_item_simple('Chemistry', 'h6'),
                    wrap_item_simple('Physics 1', 'h6'),
                ]),
                wrap_items(children1: [
                    // wrap_collapse_control('Syracuse University Project Advance', 'h5', shown: true, target: 'education-hewlett-courses-supa'),
                    wrap_item_simple('Syracuse University Project Advance', 'h5'),
                ]),
                wrap_container('education-hewlett-courses-supa', shown: true, children: [
                    wrap_items(children1: [
                        wrap_head('Economic Ideas and Issues', 'h6'),
                    ], children2: [
                        wrap_head('ECN 203', 'h6'),
                    ]),
                    wrap_items(children1: [
                        wrap_head('An Introduction to the Analysis of Public Policy', 'h6'),
                    ], children2: [
                        wrap_head('PAF 101', 'h6'),
                    ]),
                ]),
            ]),
        ]),
    ]),

    wrap_section('Skills', 'h2', 'skills', class1: 'pb-2', children: [
        wrap_items('pt-2', children1: [
            wrap_collapse_control('Computer Science', 'h3', shown: true, target: 'skills-cs'),
        ]),
        wrap_container('skills-cs', class: 'pb-1', shown: true, children: [
            wrap_items('pt-2', children1: [
                wrap_collapse_control('Programming Language', 'h4', shown: true, target: 'skills-cs-language'),
            ]),
            wrap_container('skills-cs-language', shown: true, children: [
                wrap_item_simple('<b>Python3</b>', 'h5'),
                wrap_container('skills-cs-language-python', class: 'pb-2', shown: true, children: [
                    wrap_item_list(width: '11em', children: [
                        'atlassian-python-api',
                        'xlwings/pywin32',
                        'pyodbc',
                        'pyotp',
                        'Selenium',
                        'Scrapy',
                        'xlsxwriter',
                        'matplotlib',
                        'tk/ttkthemes',
                        'PySimpleGUI',
                    ]),
                ]),
                wrap_item_simple('<b>JavaScript</b>', 'h5'),
                wrap_item_simple('Java 8', 'h5'),
                wrap_item_simple('PHP 8.3', 'h5'),
                wrap_item_simple('C23/C++23', 'h5'),
            ]),
        ]),
    ]),

    wrap_section('Volunteer Roles', 'h2', 'volunteer', children: [
    ]),

    wrap_section('Activities', 'h2', 'activities', children: [
    ]),

    wrap_section('Projects', 'h2', 'projects', children: [
    ]),

));
echo "\n";

/*

        make_item_simple('Java 8', 'h5');
        
        make_item_simple('JavaScript', 'h5');
        
        make_item_simple('Python3', 'h5');
        // python packages
        
        make_item_simple('PHP8', 'h5');
        
        make_item_simple('C23/C++23', 'h5');
      make_container_end();
      
      make_item_start('pt-2');
        make_collapse_control('Web Development', 'h4', false, 'skills-cs-web');
      make_item_end();
      make_container_start('skills-cs-web', false);
        make_item_simple('HTML5', 'h5');
        
        make_item_simple('CSS3', 'h5');
        
        make_item_simple('Bootstrap 4', 'h5');
        make_item_simple('Atlassian User Interface', 'h5');
      make_container_end();
      
      make_item_start('pt-2');
        make_collapse_control('Database Management', 'h4', false, 'skills-cs-database');
      make_item_end();
      make_container_start('skills-cs-database', false);
        make_item_simple('MySQL 8.0', 'h5');
        make_item_simple('PostgreSQL', 'h5');
        make_item_simple('MongoDB', 'h5');
        make_item_simple('SQLite', 'h5');
      make_container_end();
      
      make_item_start('pt-2');
        make_collapse_control('Version Control', 'h4', false, 'skills-cs-version');
      make_item_end();
      make_container_start('skills-cs-version', false);
        make_item_simple('GitHub', 'h5');
        make_item_simple('Git Command Line Interface', 'h5');
      make_container_end();
    make_container_end();
    
    make_item_start('pt-3');
      make_collapse_control('Information Technology', 'h3', true, 'skills-it');
    make_item_end();
    make_container_start('skills-it', true);
      make_item_start('pt-2');
        make_collapse_control('Operating Systems', 'h4', true, 'skills-it-os');
      make_item_end();
      make_container_start('skills-it-os', true);
        make_item_start();
          make_collapse_control('Windows', 'h5', false, 'skills-it-os-windows');
        make_item_end();
        make_container_start('skills-it-os-windows', false);
          make_item_simple('Command Prompt');
          
          make_item_simple('Batch Script');
          
          make_item_simple('Registry Editor');
          
          make_item_simple('System Administration');
          
          make_item_simple('Local Machine Settings and Policies');
        make_container_end();
        
        make_item_start();
          make_collapse_control('Linux', 'h5', true, 'skills-it-os-linux');
        make_item_end();
        make_container_start('skills-it-os-linux', true);
          make_item_simple('Debian/Ubuntu/Kubuntu');
          
          make_item_simple('Bash');
          
          make_item_simple('Shell Script');
          
          make_item_simple('System Administration');
        make_container_end();
      make_container_end();
      
      make_item_start('pt-2');
        make_collapse_control('Computer Networks', 'h4', false, 'skills-it-network');
      make_item_end();
      make_container_start('skills-it-network', false);
        make_item_simple('Cat5/5e Cable Termination', 'h5');
        
        make_item_simple('Router Management', 'h5');
        
        make_item_simple('Create Access Point Router', 'h5');
        
        make_item_simple('Port Forwarding, Firewall Settings', 'h5');
      make_container_end();
      
      make_item_start('pt-2');
        make_collapse_control('Office Productivity', 'h4', false, 'skills-it-office');
      make_item_end();
      make_container_start('skills-it-office', false);
        make_item_simple('Microsoft Word', 'h5');
        
        make_item_simple('Microsoft Excel', 'h5');
        
        make_item_simple('Microsoft PowerPoint', 'h5');
        
        make_item_simple('Adobe Photoshop', 'h5');
        
        make_item_simple('GNU Image Manipulator Program', 'h5');
        
        make_item_simple('Notepad++', 'h5');
        
        make_item_simple('GNU nano (Linux command line)', 'h5');
      make_container_end();
    make_container_end();
    
    make_item_start('pt-3');
      make_collapse_control('General Technology', 'h3', false, 'skills-technology');
    make_item_end();
    make_container_start('skills-technology', false);
      make_item_start('pt-2');
        make_collapse_control('Electronics', 'h4', false, 'skills-technology-electronics');
      make_item_end();
      make_container_start('skills-technology-electronics', false);
        make_item_simple('Soldering', 'h5');
        
        make_item_simple('Simple Circuit Assembly', 'h5');
        
        make_item_simple('Breadboard', 'h5');
      make_container_end();
      
      make_item_start('pt-2');
        make_collapse_control('Live Sound System', 'h4', false, 'skills-technology-audio');
      make_item_end();
      make_container_start('skills-technology-audio');
        make_item_simple('Sound System Configuration', 'h5');
        
        make_item_simple('Analog Mixer Control', 'h5');
      make_container_end();
    make_container_end();
    
    make_item_start('pt-3');
      make_collapse_control('Communication', 'h3', true, 'skills-communication');
    make_item_end();
    make_container_start('skills-communication', true);
      make_item_start('pt-2');
        make_collapse_control('Language', 'h4', true, 'skills-communication-language');
      make_item_end();
      make_container_start('skills-communication-language', true);
        make_item_start();
          make_head('Korean', 'h5');
        make_item_middle();
          make_head('First Language', 'h6');
        make_item_end();
        
        make_item_start();
          make_head('English', 'h5');
        make_item_middle();
          make_head('Full Professional Proficiency', 'h6');
        make_item_end();
      make_container_end();
      
      make_item_start('pt-2');
        make_collapse_control('Speech', 'h4', false, 'skills-communication-speech');
      make_item_end();
      make_container_start('skills-communication-speech', false);
        make_item_simple('Public Speaking', 'h5');
        make_item_simple('Presentation', 'h5');
        make_item_simple('Teaching, Training', 'h5');
        make_item_simple('Explaining', 'h5');
      make_container_end();
    make_container_end();
  make_section_end();











  make_section_start('Work Experience', 'h2', 'work');
    make_item_start('pt-2');
      make_collapse_control('New York Institute of Technology', 'h3', true, 'work-nyit');
    make_item_middle();
      make_head('Jul.&nbsp;2016 - Dec.&nbsp;2018', 'h5');
    make_item_end();
    make_container_start('work-nyit', true);
      make_item_simple('New York, NY', 'h5');
      
      make_item_start('pt-2');
        make_head('Tutor/Assistant', 'h4');
      make_item_end();
      
      make_item_start('pt-2');
        make_collapse_control('Summary', 'h5', true, 'work-nyit-summary');
      make_item_end();
      make_container_start('work-nyit-summary', true);
        make_item_simple('In-campus tutoring as student employee', 'h5');
        
        make_item_simple('Computer Science and Mathematics Courses', 'h5');
        
        make_item_simple('Teaching concepts and helping courseworks', 'h5');
        
        make_item_simple('Active email communication with students', 'h5');
      make_container_end();
    make_container_end();
    
    make_item_start('pt-3');
      make_collapse_control('New Vision Korean Methodist Church', 'h3', true, 'work-newvision');
    make_item_middle();
      make_head('Jul.&nbsp;2016 - Current', 'h5');
    make_item_end();
    make_container_start('work-newvision', true);
      make_item_simple('East Rockaway, NY', 'h5');
      
      make_item_start('pt-2');
        make_head('Staff/Technician', 'h4');
      make_item_end();
      
      make_item_start('pt-2');
        make_collapse_control('Summary', 'h5', true, 'work-newvision-summary');
      make_item_end();
      make_container_start('work-newvision-summary', true);
        make_item_simple('Streaming worship to YouTube using Open Broadcaster Software', 'h5');
        
        make_item_simple('Setting up Live Sound System', 'h5');
        
        make_item_simple('Preparing PowerPoint Presentation', 'h5');
        
        make_item_simple('Maintaing printing and networking equipments', 'h5');
      make_container_end();
    make_container_end();
  make_section_end();
  
  make_section_start('Leadership Roles', 'h2', 'leadership');
    make_item_start('pt-2');
      make_collapse_control('Golden Key International Honour Society', 'h3', true, 'leadership-gk');
    make_item_middle();
      make_head('Sep.&nbsp;2016 - Dec.&nbsp;2018', 'h5');
    make_item_end();
    make_container_start('leadership-gk', true);
      make_item_simple('NYIT Chapter, New York, NY', 'h5');
      
      make_item_start('pt-2');
        make_head('President', 'h4');
      make_item_end();
      
      make_item_start('pt-2');
        make_collapse_control('Summary', 'h5', true, 'leadership-gk-summary');
      make_item_end();
      make_container_start('leadership-gk-summary', true);
        make_item_simple('Coordinating Events', 'h5');
        
        make_item_simple('Communicating with Chapter Advisor', 'h5');
        
        make_item_simple('Maintaing student portal, member roster', 'h5');
        
        make_item_simple('Sending email announcements', 'h5');
      make_container_end();
    make_container_end();
    
    make_item_start('pt-3');
      make_collapse_control('Institute of Electrical and Electronics Engineers', 'h3', true, 'leadership-ieee');
    make_item_middle();
      make_head('Feb.&nbsp;2018 - Dec.&nbsp;2018', 'h5');
    make_item_end();
    make_container_start('leadership-ieee', true);
      make_item_simple('NYIT Chapter, New York, NY', 'h5');
      
      make_item_start('pt-2');
        make_head('Administrator for United Engineering', 'h4');
      make_item_end();
      
      make_item_start('pt-2');
        make_collapse_control('Summary', 'h5', true, 'leadership-ieee-summary');
      make_item_end();
      make_container_start('leadership-ieee-summary', true);
        make_item_simple('Organizing shared club room', 'h5');
        
        make_item_simple('Installed and managed Linux OS in computers', 'h5');
        
        make_item_simple('Set up cluster computing, server hosting, remote access', 'h5');
      make_container_end();
    make_container_end();
    
    make_item_start('pt-3');
      make_collapse_control('FIRST Tech Challenge Robotics Team', 'h3', true, 'leadership-innovo');
    make_item_middle();
      make_head('Sep.&nbsp;2011 - May.&nbsp;2015', 'h5');
    make_item_end();
    make_container_start('leadership-innovo', true);
      make_item_simple('Hewlett Robotics Team, Hewlett, NY', 'h5');
      
      make_item_start('pt-2');
        make_head('Lead Programmer of Team 5477: Innovo', 'h4');
      make_item_end();
      
      make_item_start('pt-2');
        make_collapse_control('Summary', 'h5', true, 'leadership-innovo-summary');
      make_item_end();
      make_container_start('leadership-innovo-summary', true);
        make_item_simple('RobotC programming for Lego Mindstorm', 'h5');
        
        make_item_simple('TETRIX Motor Controller', 'h5');
        
        make_item_simple('Documentation using Engineering Notebook', 'h5');
        
        make_item_simple('Hosting Robotics Competition Events', 'h5');
      make_container_end();
      
      make_item_start('pt-2');
        make_collapse_control('Awards', 'h5', true, 'leadership-innovo-awards');
      make_item_end();
      make_container_start('leadership-innovo-awards', true);
        make_item_start();
          make_head('Hudson Valley Championship Winning Alliance', 'h5');
        make_item_middle();
          make_head('2011-12', 'h6');
        make_item_end();
        
        make_item_start();
          make_head('NYC Regional Tournament Champion Team', 'h5');
        make_item_middle();
          make_head('2012-13', 'h6');
        make_item_end();
        
        make_item_start();
          make_head('Promote Award', 'h5');
        make_item_middle();
          make_head('2012-13', 'h6');
        make_item_end();
        
        make_item_start();
          make_head('NYC Qualifier Winning Alliance, Inspire Award Winning Team', 'h5');
        make_item_middle();
          make_head('2013-14', 'h6');
        make_item_end();
        
        make_item_start();
          make_head('NYC/LI Syosset Qualifier Inspire Award Winning Team', 'h5');
        make_item_middle();
          make_head('2014-15', 'h6');
        make_item_end();
      make_container_end();
    make_container_end();
  make_section_end();
  
  make_section_start('Projects', 'h2', 'projects');
    make_item_start('pt-2');
      make_collapse_control('This Website', 'h3', true, 'projects-website');
    make_item_middle();
      make_head('Jun.&nbsp;2018 - Current', 'h5');
    make_item_end();
    make_container_start('projects-website', true);
      make_item_simple('Portfolio Website & Home Server', 'h5');
      
      make_item_start('pt-2');
        make_collapse_control('Summary', 'h5', true, 'projects-website-summary');
      make_item_end();
      make_container_start('projects-website-summary', true);
        make_item_simple('Debian/Ubuntu with Apache HTTPD server', 'h5');
        
        make_item_simple('HTML and CSS with Bootstrap 4 for responsive user interface', 'h5');
        
        make_item_simple('JavaScript for front-end code & PHP for back-end code', 'h5');
        
        make_item_simple('Synchronization using GitHub', 'h5');
        
        make_item_simple('SSH access for test workstation', 'h5');
      make_container_end();
    make_container_end();
    
    make_item_start('pt-3');
      make_collapse_control('Micromouse Project', 'h3', true, 'projects-micromouse');
    make_item_middle();
      make_head('Feb.&nbsp;2018 - Mar.&nbsp;2018', 'h5');
    make_item_end();
    make_container_start('projects-micromouse', true);
      make_item_simple('Project for IEEE Student Conference', 'h5');
      
      make_item_start('pt-2');
        make_collapse_control('Summary', 'h5', true, 'projects-micromouse-summary');
      make_item_end();
      make_container_start('projects-micromouse-summary', true);
        make_item_simple('Arduino Zero based robot', 'h5');
        
        make_item_simple('Utilized motor encoders and IR sensors', 'h5');
        
        make_item_simple('Performed backtracking search on 16-by-16 maze', 'h5');
      make_container_end();
      
      make_item_start('pt-2');
        make_collapse_control('Awards', 'h5', true, 'projects-micromouse-awards');
      make_item_end();
      make_container_start('projects-micromouse-awards', true);
        make_item_start();
          make_head('Region 1 Student Conference First Place', 'h5');
        make_item_middle();
          make_head('2018', 'h6');
        make_item_end();
        
        make_item_start();
          make_head('Region 1 Student Conference First Place', 'h5');
        make_item_middle();
          make_head('2019', 'h6');
        make_item_end();
      make_container_end();
    make_container_end();
    
    make_item_start('pt-3');
      make_collapse_control('Smart Mirror Project', 'h3', true, 'projects-mirror');
    make_item_middle();
      make_head('Sep.&nbsp;2018 - Dec.&nbsp;2018', 'h5');
    make_item_end();
    make_container_start('projects-mirror', true);
      make_item_simple('Coursework for Senior Project: CSCI 455', 'h5');
      
      make_item_start('pt-2');
        make_collapse_control('Summary', 'h5', true, 'projects-mirror-summary');
      make_item_end();
      make_container_start('projects-mirror-summary', true);
        make_item_simple('Raspberry-Pi based smart display with mirror', 'h5');
        
        make_item_simple('Python-based program with Graphicsl User Interface', 'h5');
        
        make_item_simple('Displays useful information such as weather or train times', 'h5');
        
        make_item_simple('Integrates OpenCV face recognition for user detection', 'h5');
        
        make_item_simple('GitHub repository was included in Arctic Code Vault', 'h5');
      make_container_end();
    make_container_end();
    
    make_item_start('pt-3');
      make_collapse_control('Child Location Tracking System', 'h3', true, 'projects-tracking');
    make_item_middle();
      make_head('Mar.&nbsp;2018 - May.&nbsp;2018', 'h5');
    make_item_end();
    make_container_start('projects-tracking', true);
      make_item_simple('Coursework for Intro to Software Engineering: CSCI 380', 'h5');
      
      make_item_start('pt-2');
        make_collapse_control('Summary', 'h5', true, 'projects-tracking-summary');
      make_item_end();
      make_container_start('projects-tracking-summary', true);
        make_item_simple('Web Application for parents to see children\'s location', 'h5');
        
        make_item_simple('HTML, CSS, Javascript for front-end', 'h5');
        
        make_item_simple('PHP, and MySQL for back-end', 'h5');
        
        make_item_simple('Demonstrate software engineering principles', 'h5');
        
        make_item_simple('Work in team environment using GitHub', 'h5');
      make_container_end();
    make_container_end();
    
    make_item_start('pt-3');
      make_collapse_control('8-Puzzle Solver', 'h3', true, 'projects-puzzle');
    make_item_middle();
      make_head('Feb.&nbsp;2017 - Apr.&nbsp;2017', 'h5');
    make_item_end();
    make_container_start('projects-puzzle', true);
      make_item_simple('Coursework for Artificial Intelligence I: CSCI 355', 'h5');
      
      make_item_start('pt-2');
        make_collapse_control('Summary', 'h5', true, 'projects-puzzle-summary');
      make_item_end();
      make_container_start('projects-puzzle-summary', true);
        make_item_simple('Used A* search algorithm to develop solution for 8-puzzle', 'h5');
        
        make_item_simple('Python-based program with command-line interface', 'h5');
        
        make_item_simple('Constructed different heuristic functions to study various efficiencies', 'h5');
        
        make_item_simple('Program is modified to perform search on larger size puzzles', 'h5');
      make_container_end();
    make_container_end();
  make_section_end();
  
  make_section_start('', 'h6', null, false, false);
  make_section_end();
  */
?>
</div>

</body>

</html>
