<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/core.php');
  require_https();
?>
<!DOCTYPE html>
<html>

<head>
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <title>Authentication</title>
</head>

<body onload="Core.Window.setTitle('Authentication')">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>

<div class="body">
  <div class="p-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="">Authentication</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">Content</h2>
        </div>
      </div>
    </div>
  </div>
</div>

</body>

</html>
