<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/core.php');
  require_https();
?>
<!DOCTYPE html>
<html>

<head>
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <title>Authentication</title>
</head>

<body onload="Core.Window.setTitle('Authentication')">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>

<div class="body">
  <div class="p-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="">Authentication</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container" id="main">
      <div class="row">
        <div class="col-md-6">
          <h2 class="">Enter your email.</h2>
          <form id="form-main" class="" action="" onsubmit="return false;">
            <div class="form-group">
              <label form="form-main" for="form-main-email">Email address:</label>
              <input type="email" class="form-control" id="form-main-email" placeholder="Enter email">
            </div>
            <button type="submit" class="btn btn-primary" id="form-main-submit">Submit</button>
          </form>
        </div>
      </div>
    </div>
    <div class="container" id="auth" hidden>
      <div class="row">
        <div class="col-md-6">
          <h2 class="">Enter received code.</h2>
          <form id="form-auth" class="" action="" onsubmit="console.log(1); return false;">
            <div class="form-group">
              <label form="form-auth" for="form-auth-code">Authentication code:</label>
              <input type="text" class="form-control" id="form-auth-code" placeholder="Enter code" autocomplete="off">
            </div>
            <button type="submit" class="btn btn-primary" id="form-auth-submit">Submit</button>
            <button type="button" class="btn btn-primary" id="success-button" onclick="return false; //Script.backToForm()">Back</button>
          </form>
        </div>
      </div>
    </div>
    <div class="container" id="wait" hidden>
      <div class="row">
        <div class="col-md-6">
          <h2 class="">Processing...</h2>
          <p class="lead" id="wait-body">Please wait.</p>
        </div>
      </div>
    </div>
    <div class="container" id="fail" hidden>
      <div class="row">
        <div class="col-md-6">
          <h2 class="">Error.</h2>
          <p class="lead" id="fail-body"></p>
          <button type="button" class="btn btn-primary" id="fail-button" onclick="return false; //Script.backToForm()">Back</button>
        </div>
      </div>
    </div>
    <div class="container" id="success" hidden>
      <div class="row">
        <div class="col-md-6">
          <h2 class="">Success.</h2>
          <p class="lead" id="success-body"></p>
          <button type="button" class="btn btn-primary" id="success-button" onclick="return false; //Script.backToForm()">Back</button>
        </div>
      </div>
    </div>
  </div>
</div>

</body>

</html>
