<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <title>scripts</title>
</head>

<body onload="Core.Window.setTitle('scripts')">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>
  <div class="p-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="">Scripts</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">him-get automated scripts</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <ul class="">
            <li>
              <h3 class="">
                <a href="./him-get.sh">him-get.sh</a>
              </h3>
            </li>
            <li>
              <h3 class="">
                <a href="./get-him-get.sh">get-him-get.sh</a>
              </h3>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">List of scripts</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <table class="table" id="table1">
            <thead class="thead-light">
              <tr>
                <th scope="col">Script</th>
                <th scope="col">Description</th>
                <th scope="col">Version</th>
                <th scope="col">Note</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row"><a href="./him-get.sh"><b>him-get</b></a></th>
                <td>Script executer.</td>
                <td>1.27</td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./get-him-get.sh"><b>get-him-get</b></a></th>
                <td>Get him-get.</td>
                <td>1.0</td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./apache.sh">apache</a></th>
                <td>Apache permission tool.</td>
                <td>1.7</td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./arch-install-part-1.sh">arch-install-part-1</a></th>
                <td>Arch Linux installation script 1.</td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./arch-install-part-2.sh">arch-install-part-2</a></th>
                <td>Arch Linux installation script 2.</td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./easyscreen.sh"><b>easyscreen</b></a></th>
                <td>Screen utility helper.</td>
                <td>1.4</td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./firewall.sh">firewall</a></th>
                <td>ufw configuration tool.</td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./hangup.sh">hangup</a></th>
                <td>Simultaneous ping utility.</td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./hosts.sh">hosts</a></th>
                <td>Intranet host name script.</td>
                <td>1.6</td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./install.sh"><b>install</b></a></th>
                <td>apt package installer.</td>
                <td>1.3</td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./lookup.sh">lookup</a></th>
                <td>name server reverse lookup.</td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./mysql.sh">mysql</a></th>
                <td>MySQL configuration tool.</td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./ntp.sh">ntp</a></th>
                <td>NTP server configuration tool.</td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./proxy.sh">proxy</a></th>
                <td>NYIT proxy configuration tool.</td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./scripts.sh">scripts</a></th>
                <td>Quick script utility.</td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./ssh.sh"><b>ssh</b></a></th>
                <td>SSH command executer.</td>
                <td>1.22</td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./webpage.sh">webpage</a></th>
                <td>Default webpage setup tool.</td>
                <td></td>
                <td></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">List of resources</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <table class="table" id="table2">
            <thead class="thead-light">
              <tr>
                <th scope="col">Resource</th>
                <th scope="col">Description</th>
                <th scope="col">Note</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row"><a href="./blacklist.txt">blacklist.txt</a></th>
                <td>Firewall blacklist.</td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./host-list-all.txt">host-list-all.txt</a></th>
                <td>All possible machine hostnames.</td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./host-list-linux.txt"><b>host-list-linux.txt</b></a></th>
                <td>All Linux machine hostnames.</td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./host-list-mint.txt">host-list-mint.txt</a></th>
                <td>All Linux Mint machine hostnames.</td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./ip-list-all.txt">ip-list-all.txt</a></th>
                <td>All possible machine ip and hostnames.</td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./ip-list-linux.txt">ip-list-linux.txt</a></th>
                <td>All Linux machine ip and hostnames.</td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./ip-list-mint.txt">ip-list-mint.txt</a></th>
                <td>All Linux Mint machine hostnames.</td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./mysqlsetup.sql">mysqlsetup.sql</a></th>
                <td>SQL initial setup script.</td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./mysqlslave.sql">mysqlslave.sql</a></th>
                <td>SQL slave node setup script.</td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"><a href="./package-list.txt"><b>package-list.txt</b></a></th>
                <td>List of apt packages to install.</td>
                <td></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <script>
    Core.Util.makeSortable(document.getElementById('table1'));
    Core.Util.makeSortable(document.getElementById('table2'));
  </script>
</body>

</html>
