<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <title>scripts</title>
</head>

<body onload="setTitle('scripts')">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>
  <div class="p-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="">Scripts</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">him-get automated scripts</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <ul class="">
            <li>
              <h3 class="">
                <a href="./him-get.sh">him-get.sh</a>
              </h3>
            </li>
            <li>
              <h3 class="">
                <a href="./get-him-get.sh">get-him-get.sh</a>
              </h3>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</body>

</html>
