<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/core.php');
?>
<!DOCTYPE html>
<html>

<head>
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <link rel="stylesheet" href="style.css">
  <script src="script.js"></script>
  <title>word clock</title>
</head>

<body onload="Core.Window.setTitle('word clock'); Script.setup();">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>

<div class="body">
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="">Word Clock</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="p-1">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p class="line" id="line1"> <b class="item" id="item-it">It</b>&nbsp;&nbsp;<b class="item" id="item-is">is</b>&nbsp;&nbsp;<b class="item" id="item-half">half</b>&nbsp;&nbsp;<b class="item" id="item-quarter">quarter</b>&nbsp;&nbsp;<b class="item" id="item-ten">ten</b>&nbsp; </p>
          <p class="line" id="line2"> <b class="item" id="item-twenty">twenty</b>&nbsp;<b class="item" id="item-five">five</b>&nbsp;<b class="item" id="item-minutes">minutes</b>&nbsp;<b class="item" id="item-to">to</b>&nbsp;<b class="item" id="item-past">past</b> </p>
          <p class="line" id="line3"> &nbsp;<b class="item" id="item-1">one</b>&nbsp;&nbsp;&nbsp;<b class="item" id="item-2">two</b>&nbsp;&nbsp;&nbsp;<b class="item" id="item-3">three</b> <b class="item" id="item-4">four</b>&nbsp;&nbsp; </p>
          <p class="line" id="line4"> &nbsp;<b class="item" id="item-5">five</b>&nbsp;&nbsp;<b class="item" id="item-6">six</b>&nbsp;&nbsp;&nbsp;<b class="item" id="item-7">seven</b>&nbsp;&nbsp;<b class="item" id="item-8">eight</b>&nbsp;&nbsp; </p>
          <p class="line" id="line5"> &nbsp;<b class="item" id="item-9">nine</b>&nbsp;&nbsp;<b class="item" id="item-10">ten</b>&nbsp;&nbsp;<b class="item" id="item-11">eleven</b>&nbsp;&nbsp;<b class="item" id="item-12">twelve</b>&nbsp; </p>
          <p class="line" id="line6"> <b class="item" id="item-noon">noon</b>&nbsp;<b class="item" id="item-midnight">midnight</b>&nbsp;<b class="item" id="item-clock">o'clock</b>&nbsp;<b class="item" id="item-am">AM</b>&nbsp;<b class="item" id="item-pm">PM</b> </p>
          <p class="line" id="line7"> <b class="item" id="item-indicator">...</b>
        </div>
      </div>
    </div>
  </div>
</div>

</body>

</html>
