<?php
  require_once('redirect.php');
?>

<!DOCTYPE html>
<html>

<head>
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <title>URL shortening &amp; redirect</title>
</head>

<body onload="setTitle('URL shortening &amp; redirect')">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>

<div class="body">
  <div class="p-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="">URL shortening &amp; redirect</h1>
        </div>
      </div>
    </div>
  </div>

<?php
  if ($error) {
?>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">Error.</h2>
          <p class="lead">
             <?php echo $message; ?>
          </p>
        </div>
      </div>
    </div>
  </div>
<?php
  } else {
?>
  <div class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">Create new URL.</h2>
          <form class="" action="">
            <div class="form-group">
              <label for="Expires">Expires after:</label>
              <select class="form-control" id="form-expires">
                <option selected value="null">Never</option>
                <option value="10800">3 hours</option>
                <option value="21600">6 hours</option>
                <option value="43200">12 hours</option>
                <option value="86400">24 hours</option>
                <option value="604800">7 days</option>
                <option value="2592000">30 days</option>
                <option value="15778463">6 months</option>
                <option value="31556926">12 months</option>
                <option value="63113852">24 months</option>
              </select>
            </div>
            <div class="form-group">
              <label for="URL">Destination URL:</label>
              <input type="url" class="form-control" id="form-url" placeholder="Enter URL">
            </div>
            <button type="submit" class="btn btn-primary" id="form-button" onclick="alert('hello')">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
<?php
  }
?>

</div>
</body>

</html>
