<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/core.php');
  require_https();
  
  require_once('redirect.php');
?>

<!DOCTYPE html>
<html>

<head>
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <script src="script.js"></script>
  <title>URL shortening &amp; redirect</title>
</head>

<body onload="Core.Window.setTitle('URL shortening &amp; redirect');">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>

<div class="body">
  <div class="p-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="">URL shortening &amp; redirect</h1>
        </div>
      </div>
    </div>
  </div>

<?php
  if (sizeof($_GET) == 0) {
?>
  <div class="p-3">
    <div class="container" id="main">
      <div class="row">
        <div class="col-md-6">
          <h2 class="">Create new URL.</h2>
          <form class="" action="" onsubmit="return Script.submitForm()">
            <div class="form-group">
              <label for="form-expires">Expires after:</label>
              <select class="form-control" id="form-expires">
                <option selected value="">Never</option>
                <option value="3 hour">3 hours</option>
                <option value="6 hour">6 hours</option>
                <option value="12 hour">12 hours</option>
                <option value="24 hour">24 hours</option>
                <option value="7 day">7 days</option>
                <option value="30 day">30 days</option>
                <option value="6 month">6 months</option>
                <option value="12 month">12 months</option>
                <option value="24 month">24 months</option>
              </select>
            </div>
            <div class="form-group">
              <label for="form-url">Destination URL:</label>
              <input type="url" class="form-control" id="form-url" placeholder="Enter URL">
            </div>
            <button type="submit" class="btn btn-primary" id="form-button">Create</button>
          </form>
        </div>
      </div>
    </div>
    <div class="container" id="wait" hidden>
      <div class="row">
        <div class="col-md-6">
          <h2 class="">Processing...</h2>
          <p class="lead" id="wait-body">Please wait.</p>
        </div>
      </div>
    </div>
    <div class="container" id="fail" hidden>
      <div class="row">
        <div class="col-md-6">
          <h2 class="">Error.</h2>
          <p class="lead" id="fail-body"></p>
          <button type="submit" class="btn btn-primary" id="fail-button" onclick="Script.backToForm()">Back</button>
        </div>
      </div>
    </div>
    <div class="container" id="success" hidden>
      <div class="row">
        <div class="col-md-6">
          <h2 class="">Created.</h2>
          <p class="lead" id="success-body"></p>
          <button type="submit" class="btn btn-light" id="success-button-copy" onclick="Script.copyToClipboard()">Copy</button>
          <button type="submit" class="btn btn-primary" id="success-button-go" onclick="Script.goToURL()"><b>Go</b></button>
          <button type="submit" class="btn btn-primary" id="success-button" onclick="Script.backToForm()">Back</button>
          <p class="" id="success-info" hidden><label for="confirm" id="success-label"></label></p>
        </div>
      </div>
    </div>
  </div>
<?php
  } elseif ($error) {
?>
  <div class="p-3" id="error">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">Error.</h2>
          <p class="lead" id="error-body"><?php echo $message; ?></p>
        </div>
      </div>
    </div>
  </div>
<?php
  } else {
?>
  <div class="p-3" id="unknown">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="">Error.</h2>
          <p class="lead" id="unknown-body">
            Something terribly went wrong. This should not happen...... <br>
            Please reload the page.
          </p>
        </div>
      </div>
    </div>
  </div>
<?php
  }
?>

</div>
</body>

</html>
