<!DOCTYPE html>
<html>

<head>
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <link rel="stylesheet" href="style.css">
  <script src="script.js"></script>
  <title>Chat</title>
</head>

<body onload="Core.Window.setTitle('Chat'); Core.Window.setProtocol('https:'); Script.start();">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>

<?php
  require_once('initialize.php');
?>

<div class="body">
  <div class="p-1 h-100">
    <div class="container bg-light chat-area" id="chat-area">
<!--
      <div class="row" id="1">
        <div class="col-md-12">
          <p class="m-0">username (0.0.0.0) @ timestamp</p>
          <p class="chat-text px-1 m-0 mr-2">chat content</p>
        </div>
      </div>
-->
    </div>
  </div>
  <div class="p-1 fixed-bottom">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <form class="" action="" autocomplete="off" name="chat-form" onsubmit="return Script.send()">
            <div class="d-flex flex-row">
              <input class="form-control mr-2" type="text" id="chat-input" autocomplete="off">
              <button class="btn btn-primary" type="submit" id="chat-submit">Send</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="p-2 position-relative">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          &nbsp;
        </div>
      </div>
    </div>
  </div>

</body>

</html>
