<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/core.php');
  require_https();
  
  require_once('initialize.php');
?>
<!DOCTYPE html>
<html>

<head>
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <link rel="stylesheet" href="style.css">
  <script src="script.js"></script>
  <title>Chat</title>
</head>

<body onload="Core.Window.setTitle('Chat'); Script.start();">
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/navbar.html');
?>

<div class="body">
  <div class="p-1 h-100 chat-wrapper">
    <div class="container chat-wrapper chat-background py-2 pr-0 h-100 bg-light">
      <div class="chat-area h-100" id="chat-area">
<!--
        <div class="row mr-0" id="0">
          <div class="col-md-12">
            <p class="m-0">username (0.0.0.0) @ timestamp</p>
            <p class="chat-text px-1 m-0 mr-2">chat content</p>
          </div>
        </div>
-->
      </div>
    </div>
  </div>
  <div class="p-1">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <form class="" action="" autocomplete="off" name="chat-form" onsubmit="return Script.send()">
            <div class="d-flex flex-row">
              <input class="form-control mr-2" type="text" id="chat-input" autocomplete="off">
              <button class="btn btn-primary" type="submit" id="chat-submit">Send</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
</body>

</html>
