<!DOCTYPE html>
<html ondblclick="Core.Window.toggleFullscreen()">
<head>
<?php
  require_once($_SERVER['DOCUMENT_ROOT'].'/header.html');
?>
  <link rel="stylesheet" href="style.css">
  <title id="title">Color</title>
  <style>
    html {
<?php
    if (isset($_GET['background'])) {
        if (ctype_xdigit($_GET['background'])) {
            echo 'background-color: #'.$_GET['background'].";\r\n";
        } else {
            echo 'background-color: '.htmlspecialchars($_GET['background']).";\r\n";
        }
    }
    if (isset($_GET['foreground'])) {
        if (ctype_xdigit($_GET['background'])) {
            echo 'color: #'.$_GET['background'].";\r\n";
        } else {
            echo 'color: '.htmlspecialchars($_GET['foreground']).";\r\n";
        }
    }
    if (isset($_GET['font'])) {
        echo 'font-family: '.htmlspecialchars($_GET['font']).";\r\n";
    }
    if (isset($_GET['size'])) {
        echo 'font-size: '.htmlspecialchars($_GET['size']).";\r\n";
    }
    if (isset($_GET['weight'])) {
        echo 'font-weight: '.htmlspecialchars($_GET['weight']).";\r\n";
    }
    if (isset($_GET['style'])) {
        echo 'font-style: '.htmlspecialchars($_GET['style']).";\r\n";
    }
?>
    }
  </style>
</head>
<body class="main" id="main" onload="Core.Window.setTitle('Color')">
  <div class="box" id="box">
    <p class="text" id="text">
<?php
    if (isset($_GET['text'])) {
        echo htmlspecialchars($_GET['text']);
    }
?>
    </p>
  </div>
</body>
